"""Defender XDR + Defender for Cloud Apps security posture.

Two peer domains on one board because they answer one question — "what is
attacking or exposed" — from two products that are reached over different
transports: `defender.*` over Azure Storage blob ingest (advanced-hunting export),
`mdca.*` over the legacy Defender for Cloud Apps portal API. Both are opt-in, so
every panel here is empty until the matching configuration is set, and says so.
"""

DOMAIN = "Defender"
DESCRIPTION = (
    "Microsoft Defender XDR vulnerability, software, secure-configuration, tenant "
    "allow/block-list, Defender for Office 365 and OAuth-app posture, plus Defender for "
    "Cloud Apps Cloud Discovery parse health — with the advanced-hunting log twins. "
    "Blob ingest (blob_ingest.account_url) drives the defender.* signals; mdca.* needs "
    "mdca.portal_url + mdca.token_file. Generated by grafana/build_dashboard.py from "
    "spec/signal-catalog.json — edit grafana/boards/defender_security.py, not this JSON."
)
AVAILABILITY_PATTERN = r"(?:defender|mdca)\..+"

SECTIONS = [
    ("Vulnerabilities and software", [
        "defender.vulnerability.cves",
        "defender.vulnerability.instances",
        "defender.vulnerability.affected_devices",
        "defender.vulnerability.max_cvss",
        "defender.vulnerability.max_epss",
        "defender.software.products",
        "defender.software.installs",
        "defender.software.eos_devices",
    ]),
    ("Secure configuration", [
        "defender.secure_config.assessments",
        "defender.secure_config.noncompliant_devices",
        "defender.secure_config.impact_at_risk",
    ]),
    ("Tenant allow/block list", [
        "defender.allow_block_list.entries",
        "defender.allow_block_list.expiring_soon",
        "defender.allow_block_list.non_expiring_allow",
        "defender.allow_block_list.spoof_entries",
    ]),
    ("Defender for Office 365", [
        "defender.mdo.policies",
        "defender.mdo.protection_enabled",
        "defender.quarantine.held_messages.total",
        # #354, the rule layer. A policy says what protection is applied; a rule
        # says to whom. The two panels that matter are the last two: an
        # unreferenced policy is configured and inert, and an unscoped enabled
        # rule applies org-wide — read together they answer "is preset
        # protection actually reaching anyone", which the policy panels above
        # structurally cannot.
        "defender.mdo.rules",
        "defender.mdo.rules.conditions",
        "defender.mdo.rules.unscoped",
        "defender.mdo.unreferenced_policies",
    ]),
    ("Exposure graph (opt-in: hunting.enabled)", [
        # #350. node_label and edge_label are Microsoft's own ontology, so a
        # table by label IS the census. `twinned` is the load-bearing dimension:
        # it distinguishes "we saw nothing" from "we deliberately did not twin
        # 990,000 CVE and recommendation nodes", which on a raw count panel look
        # identical.
        ("Exposure graph nodes by label (twinned=false is bulk inventory, counted not twinned)",
         ["defender.exposure_graph.nodes"], {"viz": "table", "w": 12, "h": 8}),
        ("Exposure graph edges by label", ["defender.exposure_graph.edges"],
         {"viz": "table", "w": 12, "h": 8}),
        "defender.exposure_graph.excluded_labels",
    ]),
    ("OAuth apps", [
        "defender.oauth_app.apps",
        "defender.oauth_app.consented_users",
        "defender.oauth_app.max_risk_score",
    ]),
    ("Defender for Cloud Apps — Cloud Discovery (Experimental, opt-in)", [
        "mdca.discovery.parse.tasks",
        "mdca.discovery.parse.last_success.age",
        "mdca.discovery.parse.transactions",
        "mdca.discovery.parse.cloud_services",
    ]),
    ("Defender for Cloud Apps — discovered shadow IT (Experimental, opt-in)", [
        # #361. A different transport from the parse-health panels above:
        # those reach the legacy portal API, these are Graph beta. Category
        # is the only per-app dimension that is bounded, so the app inventory
        # reads as a table by category rather than as a per-app series.
        ("Discovered apps by category (generativeAi is usually the one being looked for)",
         ["mdca.cloud_discovery.apps"], {"viz": "table", "w": 12, "h": 8}),
        ("Discovered apps by risk band", ["mdca.cloud_discovery.apps.by_risk"],
         {"viz": "timeseries"}),
        ("Upload streams and log files ingested",
         ["mdca.cloud_discovery.streams", "mdca.cloud_discovery.log_files.total"],
         {"viz": "timeseries"}),
        # A capped app scan reports a partial view; without this panel a
        # truncated inventory is indistinguishable from a small one.
        "mdca.cloud_discovery.apps_truncated",
    ]),
]

LOGS = [
    {"kind": "logs", "event": "defender.alert_info",
     "title": "Defender alerts — which alert, which source",
     "w": 24, "h": 12},
    {"kind": "table", "event": "defender.alert_info",
     "title": "Alerts by severity and detection source",
     "by": ["severity", "detection_source"]},
    {"kind": "table", "event": "defender.vulnerability",
     "title": "Top vulnerable software (which CVE, which device)",
     "by": ["software_name", "severity"]},
    {"kind": "table", "event": "defender.exposure_graph_node",
     "title": "Exposure graph — the investigable entities, by label and category",
     "by": ["node_label", "categories"]},
    {"kind": "logs", "event": "defender.mdo_rule",
     "title": "MDO protection rules — which policy reaches whom, in what priority",
     "desc": "Recipient addresses, groups and domains are structured metadata here and "
             "never metric labels (#112). Empty unless exchange_online.enabled is set.",
     "w": 24, "h": 10},
    {"kind": "rate", "event": "defender.device_logon",
     "title": "Device logon rate by logon type",
     "by": ["logon_type", "action_type"]},
    {"kind": "logs", "event": "mdca.discovery_parse",
     "title": "Cloud Discovery parse tasks — which stream, which template",
     "desc": "The one non-Graph, non-azidentity credential in the project: a static "
             "portal token. Empty unless mdca.portal_url and mdca.token_file are set.",
     "w": 24, "h": 10},
]
