"""Defender XDR + Defender for Cloud Apps security posture.

Two peer domains on one board because they answer one question — "what is
attacking or exposed" — from two products that are reached over different
transports: `defender.*` over Azure Storage blob ingest (advanced-hunting export),
`mdca.*` over the legacy Defender for Cloud Apps portal API. Both are opt-in, so
every panel here is empty until the matching configuration is set, and says so.
"""

UID = "graph2otel-defender-security"
TITLE = "graph2otel: Defender security posture"
DESCRIPTION = (
    "Microsoft Defender XDR vulnerability, software, secure-configuration, tenant "
    "allow/block-list, Defender for Office 365 and OAuth-app posture, plus Defender for "
    "Cloud Apps Cloud Discovery parse health — with the advanced-hunting log twins. "
    "Blob ingest (blob_ingest.account_url) drives the defender.* signals; mdca.* needs "
    "mdca.portal_url + mdca.token_file. Generated by grafana/build_dashboard.py from "
    "spec/signal-catalog.json — edit grafana/boards/defender_security.py, not this JSON."
)
TAGS = ["graph2otel", "defender", "mdca", "security", "generated"]
TENANT_METRIC = "defender_vulnerability_cves"

SECTIONS = [
    ("Vulnerabilities and software", [
        "defender.vulnerability.cves",
        "defender.vulnerability.instances",
        "defender.vulnerability.affected_devices",
        "defender.vulnerability.max_cvss",
        "defender.vulnerability.max_epss",
        "defender.software.products",
        "defender.software.installs",
        "defender.software.eos_devices",
    ]),
    ("Secure configuration", [
        "defender.secure_config.assessments",
        "defender.secure_config.noncompliant_devices",
        "defender.secure_config.impact_at_risk",
    ]),
    ("Tenant allow/block list", [
        "defender.allow_block_list.entries",
        "defender.allow_block_list.expiring_soon",
        "defender.allow_block_list.non_expiring_allow",
        "defender.allow_block_list.spoof_entries",
    ]),
    ("Defender for Office 365", [
        "defender.mdo.policies",
        "defender.mdo.protection_enabled",
        "defender.quarantine.held_messages.total",
    ]),
    ("OAuth apps", [
        "defender.oauth_app.apps",
        "defender.oauth_app.consented_users",
        "defender.oauth_app.max_risk_score",
    ]),
    ("Defender for Cloud Apps — Cloud Discovery (Experimental, opt-in)", [
        "mdca.discovery.parse.tasks",
        "mdca.discovery.parse.last_success.age",
        "mdca.discovery.parse.transactions",
        "mdca.discovery.parse.cloud_services",
    ]),
]

LOGS = [
    {"kind": "logs", "event": "defender.alert_info",
     "title": "Defender alerts — which alert, which source",
     "w": 24, "h": 12},
    {"kind": "table", "event": "defender.alert_info",
     "title": "Alerts by severity and detection source",
     "by": ["severity", "detection_source"]},
    {"kind": "table", "event": "defender.vulnerability",
     "title": "Top vulnerable software (which CVE, which device)",
     "by": ["software_name", "severity"]},
    {"kind": "rate", "event": "defender.device_logon",
     "title": "Device logon rate by logon type",
     "by": ["logon_type", "action_type"]},
    {"kind": "logs", "event": "mdca.discovery_parse",
     "title": "Cloud Discovery parse tasks — which stream, which template",
     "desc": "The one non-Graph, non-azidentity credential in the project: a static "
             "portal token. Empty unless mdca.portal_url and mdca.token_file are set.",
     "w": 24, "h": 10},
]
