"""Entra ID compliance overview — directory posture, identity risk, sign-ins."""

UID = "graph2otel-entra-compliance"
TITLE = "graph2otel: Entra ID compliance overview"
DESCRIPTION = (
    "Entra ID directory, licensing, application, policy, role, secure-score, MFA and "
    "risk posture, plus the log twins that name the user, app or sign-in behind each "
    "number. Generated by grafana/build_dashboard.py from spec/signal-catalog.json — "
    "edit grafana/boards/entra_compliance.py, not this JSON."
)
TAGS = ["graph2otel", "entra", "compliance", "generated"]
TENANT_METRIC = "entra_users_total"

SECTIONS = [
    ("Directory objects", [
        "entra.directory.objects.total",
        "entra.users.total",
        "entra.users.population",
        "entra.users.stale.total",
        "entra.devices.total",
        "entra.devices.stale.total",
        "entra.devices.compliance.total",
        "entra.devices.managed.total",
        "entra.devices.os.total",
        "entra.groups.total",
        "entra.groups.role_assignable.total",
        "entra.domains.total",
        ("Federated and verified domains",
         ["entra.domains.federated.total", "entra.organization.verified_domains.total"]),
        "entra.deleted_items.count",
        "entra.directory.sync.errors.total",
        ("Directory sync freshness",
         ["entra.directory.sync.last_sync_age_seconds",
          "entra.organization.on_premises_sync_enabled"]),
        ("Tenant", ["entra.organization.info", "entra.organization.age_days"],
         {"viz": "table", "w": 24, "h": 6}),
    ]),
    ("Licensing", [
        "entra.license.consumed",
        "entra.license.enabled",
        "entra.license.units",
        "entra.license.capability_status",
        "entra.license.groups_with_errors.total",
    ]),
    ("Applications, service principals and credentials", [
        "entra.credentials.expiring.total",
        "entra.application.federated_credentials",
        "entra.application.ownership",
        "entra.service_principal.ownership",
        "entra.consent.grants.total",
        "entra.app.signin.summary.total",
        ("Stale credential and service-principal sign-ins",
         ["entra.app.credential.signin.stale.total",
          "entra.serviceprincipal.signin.stale.total"]),
    ]),
    ("Policy and Conditional Access", [
        "entra.ca.policies.total",
        "entra.named_locations.total",
        "entra.auth_methods_policy.legacy_enabled.total",
        ("Auth method policy: enabled methods", ["entra.auth_methods_policy.method.enabled"],
         {"viz": "table", "w": 12, "h": 8}),
        "entra.tenant_policy.scoped_policies",
        ("Tenant policy settings", ["entra.tenant_policy.setting"],
         {"viz": "table", "w": 12, "h": 8}),
        "entra.agreements.total",
        "entra.agreements.acceptances.total",
    ]),
    ("Roles, PIM and access reviews", [
        "entra.roles.members.total",
        "entra.pim.assignments.total",
        "entra.pim.permanent_assignments.total",
        "entra.pim.alert.count",
        "entra.pim.alert.incidents",
        "entra.pim.alert.configurations",
        ("PIM role policy requirements", ["entra.pim.role_policy.requirement"],
         {"viz": "table", "w": 12, "h": 8}),
        "entra.access_reviews.total",
    ]),
    ("Secure score and recommendations", [
        ("Secure score current vs max",
         ["entra.secure_score.current", "entra.secure_score.max"],
         {"viz": "timeseries"}),
        "entra.secure_score.percentage",
        "entra.secure_score.by_category",
        "entra.secure_score.max_by_category",
        "entra.secure_score.peer_average",
        "entra.secure_score.control_profiles.by_category",
        "entra.secure_score.control_profiles.by_status",
        "entra.recommendations.total",
        "entra.recommendations.impacted_resources.total",
    ]),
    ("MFA and authentication methods", [
        "entra.mfa.registration.users.total",
        "entra.mfa.registration.methods.total",
        "entra.mfa.registration.admin_mfa_capable.total",
    ]),
    ("Risk and sign-ins (Entra ID P2 for the risk signals)", [
        "entra.risky_users.total",
        "entra.risky_service_principals.total",
        "entra.risky_agents.total",
        "entra.signin.count",
    ]),
    ("Global Secure Access (beta, opt-in)", [
        "entra.gsa.onboarding_status",
        "entra.gsa.forwarding_profiles",
        "entra.gsa.filtering_policies",
        "entra.gsa.remote_networks",
        ("GSA tenant switches",
         ["entra.gsa.packet_tagging_enabled", "entra.gsa.signaling_enabled"]),
    ]),
    ("Graph API activity (blob ingest, opt-in)", [
        "entra.graph_activity.requests",
        "entra.graph_activity.endpoint_requests",
        "entra.graph_activity.request.duration",
        "entra.graph_activity.response.size",
    ]),
]

LOGS = [
    {"kind": "logs", "event": "entra.signin",
     "title": "Failed sign-ins — which user, which IP, which error",
     "filters": ["status_error_code!=`0`"],
     "desc": "The metric says how many sign-ins failed. This says whose. Error 53004 is "
             "the Tor/anonymous-IP case #129 used to prove risk detection fires.",
     "w": 24, "h": 12},
    {"kind": "rate", "event": "entra.signin",
     "title": "Failed sign-in rate by error code",
     "filters": ["status_error_code!=`0`"], "by": ["status_error_code"]},
    {"kind": "table", "event": "entra.signin",
     "title": "Top failing sign-in sources (country, client app)",
     "filters": ["status_error_code!=`0`"],
     "by": ["location_country_or_region", "client_app_used"]},
    {"kind": "logs", "event": "entra.risk_detection",
     "title": "Risk detections — MITRE ATT&CK technique, IP, user",
     "desc": "mitre_techniques is on every risk detection (#153). Add "
             "`| mitre_techniques=~\"T1090.*\"` to this panel's query to filter to "
             "proxy/tunnelling techniques.",
     "w": 24, "h": 12},
    {"kind": "table", "event": "entra.risk_detection",
     "title": "Risk detections by event type and level",
     "by": ["risk_event_type", "risk_level"]},
    {"kind": "table", "event": "entra.directory_audit",
     "title": "Top directory audit activities",
     "by": ["activity_display_name", "result"]},
]
