"""Entra ID compliance overview — directory posture, identity risk, sign-ins."""

from logquery import f

DOMAIN = "Entra"
DESCRIPTION = (
    "Entra ID directory, licensing, application, policy, role, secure-score, MFA and "
    "risk posture, plus the log twins that name the user, app or sign-in behind each "
    "number. Generated by grafana/build_dashboard.py from spec/signal-catalog.json — "
    "edit grafana/boards/entra_compliance.py, not this JSON."
)
AVAILABILITY_PATTERN = r"entra\..+"

SECTIONS = [
    ("Directory objects", [
        "entra.directory.objects.total",
        "entra.users.total",
        "entra.users.population",
        "entra.users.stale.total",
        "entra.devices.total",
        "entra.devices.stale.total",
        "entra.devices.compliance.total",
        "entra.devices.managed.total",
        "entra.devices.os.total",
        "entra.groups.total",
        "entra.groups.role_assignable.total",
        "entra.privileged_groups.members.total",
        # Its own panel, not stacked with the member counts: accessible is a 0/1
        # reachability flag and members.total is a population, so one axis cannot
        # describe both (#304). A group that drops to accessible=0 is the signal
        # that its member count went ABSENT rather than to zero.
        ("Privileged group reachability", ["entra.privileged_groups.accessible"],
         {"viz": "table", "w": 12, "h": 6}),
        "entra.domains.total",
        ("Federated and verified domains",
         ["entra.domains.federated.total", "entra.organization.verified_domains.total"]),
        "entra.deleted_items.count",
        "entra.directory.sync.errors.total",
        "entra.directory.sync.last_sync_age_seconds",
        # Its own panel rather than sharing the freshness axes: it is a 0/1 flag
        # and the age is in seconds, so one value mapping cannot describe both
        # without relabelling the seconds (#304).
        ("Hybrid directory sync", ["entra.organization.on_premises_sync_enabled"],
         {"viz": "table", "w": 12, "h": 6}),
        ("Tenant", ["entra.organization.info", "entra.organization.age_days"],
         {"viz": "table", "w": 24, "h": 6}),
    ]),
    ("Licensing", [
        "entra.license.consumed",
        "entra.license.enabled",
        "entra.license.units",
        "entra.license.capability_status",
        "entra.license.groups_with_errors.total",
    ]),
    ("Applications, service principals and credentials", [
        "entra.credentials.expiring.total",
        "entra.application.federated_credentials",
        "entra.application.ownership",
        "entra.service_principal.ownership",
        "entra.consent.grants.total",
        "entra.app.signin.summary.total",
        ("Stale credential and service-principal sign-ins",
         ["entra.app.credential.signin.stale.total",
          "entra.serviceprincipal.signin.stale.total"]),
    ]),
    ("Policy and Conditional Access", [
        "entra.ca.policies.total",
        "entra.named_locations.total",
        "entra.auth_methods_policy.legacy_enabled.total",
        ("Auth method policy: enabled methods", ["entra.auth_methods_policy.method.enabled"],
         {"viz": "table", "w": 12, "h": 8}),
        "entra.tenant_policy.scoped_policies",
        ("Tenant policy settings", ["entra.tenant_policy.setting"],
         {"viz": "table", "w": 12, "h": 8}),
        "entra.agreements.total",
        "entra.agreements.acceptances.total",
        # Authentication-strength inventory (#322). Which strength policies
        # exist and what satisfies them — the posture Conditional Access
        # references by id but never enumerates.
        ("Authentication-strength policies", ["entra.auth_strength.policies"],
         {"viz": "table", "w": 12, "h": 8}),
    ]),
    ("Cross-tenant access (which other tenants can reach this one)", [
        # #321. The access ladder is a 0/1 posture gauge per
        # (service, direction, target_kind, access_type), so a table reads far
        # better than a time series: an operator wants "what is the boundary
        # right now", not its history.
        ("B2B / direct-connect / tenant-restriction boundaries",
         ["entra.cross_tenant_access.access"], {"viz": "table", "w": 12, "h": 8}),
        ("Inbound trust — what this tenant accepts from the OTHER tenant",
         ["entra.cross_tenant_access.inbound_trust"], {"viz": "table", "w": 12, "h": 8}),
        ("Automatic user consent (1 = consent is skipped)",
         ["entra.cross_tenant_access.automatic_user_consent"], {"viz": "timeseries"}),
        "entra.cross_tenant_access.partners.total",
    ]),
    ("Roles, PIM and access reviews", [
        "entra.roles.members.total",
        "entra.pim.assignments.total",
        "entra.pim.permanent_assignments.total",
        "entra.pim.alert.count",
        "entra.pim.alert.incidents",
        "entra.pim.alert.configurations",
        ("PIM role policy requirements", ["entra.pim.role_policy.requirement"],
         {"viz": "table", "w": 12, "h": 8}),
        "entra.access_reviews.total",
        # #319. The definition count says a review EXISTS; these two say whether
        # anyone is doing it. decision x applied_result are separate labels on
        # purpose: a decision can be Deny and still never have been applied,
        # which is the "the review ran and changed nothing" case.
        "entra.access_reviews.instances",
        "entra.access_reviews.decisions",
        # Role DEFINITIONS (#320) — what roles exist and whether they are
        # built-in/enabled, independent of who holds them. Sits beside the
        # membership counts on purpose: a custom or disabled definition has no
        # members, so it is invisible in every other panel in this section.
        ("Role definitions by built-in / enabled",
         ["entra.role_definitions.definitions"], {"viz": "timeseries"}),
    ]),
    ("Directory recoverability", [
        # #334. Age is the first panel, not the count, because that is the
        # signal: retention holds 7 daily snapshots, so the count sits flat at
        # 7 on a healthy tenant and says nothing, while the newest-snapshot age
        # is what climbs when the backup service stops taking them. A missing
        # age series means no snapshot exists at all — worse than a large one,
        # and deliberately NOT rendered as zero.
        ("Newest snapshot age",
         ["entra.directory_recovery.newest_snapshot_age"], {"viz": "timeseries"}),
        ("Retained snapshots",
         ["entra.directory_recovery.snapshots"], {"viz": "timeseries"}),
        # Both job series are panelled. The total is flat at 0 on a tenant
        # nobody has ever run a restore on, which is the point: it distinguishes
        # "no job has ever run" from "the collector stopped reporting", and the
        # by-status breakdown is empty in that same steady state.
        ("Recovery jobs",
         ["entra.directory_recovery.jobs"], {"viz": "timeseries"}),
        ("Recovery jobs by status",
         ["entra.directory_recovery.jobs_by_status"], {"viz": "timeseries"}),
    ]),
    ("Agent ID governance", [
        # #333. without_owner / without_sponsor get their own single-stat
        # panels rather than living only inside the joint gauge: "an agent
        # nobody owns" is the alertable finding, and it should be readable
        # without a query.
        ("Agents with no owner / no sponsor",
         ["entra.agent_governance.agents.without_owner",
          "entra.agent_governance.agents.without_sponsor"],
         {"viz": "timeseries"}),
        ("Agent identities by governance state",
         ["entra.agent_governance.agents"], {"viz": "table", "w": 12, "h": 8}),
        ("Blueprint principals", ["entra.agent_governance.blueprint_principals"],
         {"viz": "timeseries"}),
        "entra.agent_governance.blueprints.total",
    ]),
    ("Secure score and recommendations", [
        ("Secure score current vs max",
         ["entra.secure_score.current", "entra.secure_score.max"],
         {"viz": "timeseries"}),
        "entra.secure_score.percentage",
        "entra.secure_score.by_category",
        "entra.secure_score.max_by_category",
        "entra.secure_score.peer_average",
        "entra.secure_score.control_profiles.by_category",
        "entra.secure_score.control_profiles.by_status",
        "entra.recommendations.total",
        "entra.recommendations.impacted_resources.total",
    ]),
    ("MFA and authentication methods", [
        "entra.mfa.registration.users.total",
        "entra.mfa.registration.methods.total",
        "entra.mfa.registration.admin_mfa_capable.total",
    ]),
    ("Risk and sign-ins (Entra ID P2 for the risk signals)", [
        "entra.risky_users.total",
        "entra.risky_service_principals.total",
        "entra.risky_agents.total",
        "entra.signin.count",
    ]),
    ("Service activity — measured tenant experience (Experimental, opt-in)", [
        # #368. The counterpart to m365.service_health, which reports what
        # MICROSOFT has DECLARED. These report what the tenant actually
        # experienced, at 30-minute resolution, between declared incidents.
        # Four metrics rather than one because the units differ and a
        # mixed-unit sum would be meaningless.
        "entra.service_activity.signins",
        "entra.service_activity.network_access_apps",
        "entra.service_activity.network_access_users",
        "entra.service_activity.network_access_branches",
    ]),
    ("Related tenants — discovered tenant entanglement (beta, opt-in)", [
        # #336. Which OTHER tenants this one is entangled with, as DISCOVERED by
        # Microsoft rather than declared by an admin — the counterpart to
        # entra.cross_tenant_access, which reports configured policy.
        #
        # total is split by is_microsoft_infrastructure because 3 of 16 live rows
        # are Microsoft's own infrastructure tenants; an unsplit total overstates
        # external entanglement by exactly those.
        "entra.related_tenants.total",
        # with_metrics is the COVERAGE panel and the one to read first: four of
        # the five metric blocks are null on almost every row, so a flat zero on
        # the counters below means "Microsoft supplied no measurement", not "no
        # B2B activity". Reading the counters without this panel is how that
        # gets misread.
        "entra.related_tenants.with_metrics",
        "entra.related_tenants.b2b_registered_users",
        "entra.related_tenants.b2b_signin_users",
        "entra.related_tenants.multi_tenant_applications",
        ("Tenant governance switches",
         ["entra.related_tenants.discovery_enabled",
          "entra.related_tenants.can_receive_invitations"]),
    ]),
    ("Global Secure Access (beta, opt-in)", [
        "entra.gsa.onboarding_status",
        "entra.gsa.forwarding_profiles",
        "entra.gsa.filtering_policies",
        "entra.gsa.remote_networks",
        ("GSA tenant switches",
         ["entra.gsa.packet_tagging_enabled", "entra.gsa.signaling_enabled"]),
    ]),
    ("Graph API activity (blob ingest, opt-in)", [
        "entra.graph_activity.requests",
        "entra.graph_activity.endpoint_requests",
        "entra.graph_activity.request.duration",
        "entra.graph_activity.response.size",
    ]),
]

LOGS = [
    {"kind": "table", "event": "entra.access_review_decision",
     "title": "Access-review decisions — who is pending, and was it ever applied",
     "desc": "An undecided decision carries a ZERO-GUID reviewedBy on the wire; graph2otel drops "
             "it rather than publishing a phantom reviewer, so an absent reviewed_by_id means "
             "nobody has acted.",
     "by": ["decision", "applied_result"]},

    {"kind": "logs", "event": "entra.signin",
     "title": "Failed sign-ins — which user, which IP, which error",
     "filters": [f("status_error_code", "ne", "0")],
     "desc": "The metric says how many sign-ins failed. This says whose. Error 53004 is "
             "the Tor/anonymous-IP case #129 used to prove risk detection fires.",
     "w": 24, "h": 12},
    {"kind": "rate", "event": "entra.signin",
     "title": "Failed sign-in rate by error code",
     "filters": [f("status_error_code", "ne", "0")], "by": ["status_error_code"]},
    {"kind": "table", "event": "entra.signin",
     "title": "Top failing sign-in sources (country, client app)",
     "filters": [f("status_error_code", "ne", "0")],
     "by": ["location_country_or_region", "client_app_used"]},
    {"kind": "logs", "event": "entra.risk_detection",
     "title": "Risk detections — MITRE ATT&CK technique, IP, user",
     "desc": "mitre_techniques is on every risk detection (#153). Add "
             "`| mitre_techniques=~\"T1090.*\"` to this panel's query to filter to "
             "proxy/tunnelling techniques.",
     "w": 24, "h": 12},
    {"kind": "table", "event": "entra.risk_detection",
     "title": "Risk detections by event type and level",
     "by": ["risk_event_type", "risk_level"]},
    {"kind": "table", "event": "entra.directory_audit",
     "title": "Top directory audit activities",
     "by": ["activity_display_name", "result"]},
]
