"""Microsoft 365 service overview — Exchange, SharePoint/OneDrive, Teams, health."""

UID = "graph2otel-m365-services"
TITLE = "graph2otel: Microsoft 365 services overview"
DESCRIPTION = (
    "Exchange Online configuration and mail flow, SharePoint/OneDrive sharing and "
    "storage, Teams estate, and Microsoft 365 service health — plus the unified audit "
    "log twin. Generated by grafana/build_dashboard.py from spec/signal-catalog.json "
    "— edit grafana/boards/m365_services.py, not this JSON."
)
TAGS = ["graph2otel", "m365", "generated"]
TENANT_METRIC = "m365_service_health_services_total"

SECTIONS = [
    ("Exchange Online", [
        "m365.exchange.mailboxes",
        "m365.exchange.mailboxes.setting_enabled",
        ("Exchange audit configuration", ["m365.exchange.audit_config.enabled"],
         {"viz": "table", "w": 12, "h": 8}),
        ("Exchange org configuration", ["m365.exchange.org_config.setting_enabled"],
         {"viz": "table", "w": 12, "h": 8}),
        ("Mail-flow connectors",
         ["m365.exchange.connectors", "m365.exchange.connectors.without_tls"],
         {"viz": "timeseries"}),
        ("Transport rules",
         ["m365.exchange.transport_rules", "m365.exchange.transport_rules.redirecting"],
         {"viz": "timeseries"}),
        "m365.exchange.remote_domains",
        "m365.exchange.dkim.signing",
    ]),
    ("SharePoint and OneDrive", [
        ("SharePoint tenant sharing posture", ["m365.sharepoint.sharing"],
         {"viz": "table", "w": 12, "h": 8}),
        ("Sharing domain allow/block lists",
         ["m365.sharepoint.sharing_allowed_domains",
          "m365.sharepoint.sharing_blocked_domains"],
         {"viz": "timeseries"}),
        ("SharePoint tenant switches",
         ["m365.sharepoint.external_resharing_enabled",
          "m365.sharepoint.legacy_auth_enabled",
          "m365.sharepoint.idle_session_signout_enabled",
          "m365.sharepoint.unmanaged_sync_restricted"],
         {"viz": "timeseries", "w": 24}),
        ("Storage limits",
         ["m365.sharepoint.site_storage_limit_mb",
          "m365.sharepoint.personal_site_storage_limit_mb"],
         {"viz": "timeseries"}),
        "m365.sharepoint.deleted_user_retention_days",
        "m365.storage.drives.total",
        ("Drive storage used vs total",
         ["m365.storage.used_bytes", "m365.storage.total_bytes"],
         {"viz": "timeseries"}),
    ]),
    ("Teams", [
        "m365.teams.total",
        "m365.teams.channels.total",
        "m365.teams.membership.total",
        "m365.teams.installed_apps.total",
        ("Teams governance gaps",
         ["m365.teams.ownerless.total", "m365.teams.with_guests.total"],
         {"viz": "timeseries"}),
    ]),
    ("Service health", [
        "m365.service_health.issues.total",
        "m365.service_health.services.total",
        ("Service health status ladder", ["m365.service_health.status"],
         {"viz": "table", "w": 24, "h": 8}),
        "m365.service_messages.total",
    ]),
    ("Mail flow (message trace — HIGH VOLUME, opt-in)", [
        "m365.message_trace.messages",
        "m365.message_trace.bytes",
    ]),
]

LOGS = [
    {"kind": "logs", "event": "m365.audit",
     "title": "Unified audit — which user, which operation",
     "desc": "user_key is the opaque classic UserKey; user_id is usually the UPN but "
             "carries sentinels too. Correlate the two M365 audit transports on user_id.",
     "w": 24, "h": 12},
    {"kind": "table", "event": "m365.audit",
     "title": "Top audited operations by workload",
     "by": ["workload", "operation"]},
    {"kind": "rate", "event": "m365.audit",
     "title": "Audit record rate by result status",
     "by": ["result_status"]},
    {"kind": "table", "event": "m365.message_trace",
     "title": "Message trace: top senders (HIGH VOLUME, opt-in)",
     "by": ["sender_address", "status"],
     "desc": "One record per message per recipient — the rate scales with traffic, not "
             "tenant size. Empty unless the collector is explicitly enabled."},
]
