"""Microsoft 365 service overview — Exchange, SharePoint/OneDrive, Teams, health."""

DOMAIN = "M365"
DESCRIPTION = (
    "Exchange Online configuration and mail flow, SharePoint/OneDrive sharing and "
    "storage, Teams estate, and Microsoft 365 service health — plus the unified audit "
    "log twin. Generated by grafana/build_dashboard.py from spec/signal-catalog.json "
    "— edit grafana/boards/m365_services.py, not this JSON."
)
AVAILABILITY_PATTERN = r"m365\..+"

SECTIONS = [
    ("Exchange Online", [
        "m365.exchange.mailboxes",
        "m365.exchange.mailboxes.setting_enabled",
        ("Exchange audit configuration", ["m365.exchange.audit_config.enabled"],
         {"viz": "table", "w": 12, "h": 8}),
        ("Exchange org configuration", ["m365.exchange.org_config.setting_enabled"],
         {"viz": "table", "w": 12, "h": 8}),
        ("Mail-flow connectors",
         ["m365.exchange.connectors", "m365.exchange.connectors.without_tls"],
         {"viz": "timeseries"}),
        ("Transport rules",
         ["m365.exchange.transport_rules", "m365.exchange.transport_rules.redirecting"],
         {"viz": "timeseries"}),
        "m365.exchange.accepted_domains",
        "m365.exchange.remote_domains",
        "m365.exchange.dkim.signing",
        ("Outbound spam policy population",
         ["m365.exchange.outbound_spam.policies"], {"viz": "timeseries"}),
        ("Outbound recipient limits (default policy)",
         ["m365.exchange.outbound_spam.recipient_limit"], {"viz": "timeseries"}),
        ("Connection filter policies",
         ["m365.exchange.connection_filter.policies"], {"viz": "timeseries"}),
        ("Connection filter IP lists (non-empty allow list is the finding)",
         ["m365.exchange.connection_filter.ip_allow_list_length",
          "m365.exchange.connection_filter.ip_block_list_length"],
         {"viz": "timeseries"}),
        ("Mailbox audit bypass (audit-blinding: healthy is zero)",
         ["m365.exchange.audit_bypass.enabled_count",
          "m365.exchange.audit_bypass.examined"],
         {"viz": "timeseries"}),
        ("Mailbox quota status", ["m365.mailbox_usage.quota_status.mailboxes"],
         {"viz": "timeseries"}),
        "m365.mailbox_usage.storage_used_bytes",
        # Per-mailbox fan-out collectors (#355, #363). Coverage sits next to the
        # finding on purpose: both are capped by exo_per_mailbox, so a reader
        # who sees a delegation or rule count must be able to see in the same
        # glance whether it was measured over the whole tenant or a slice of it.
        ("Mailbox delegation (FullAccess / SendAs)",
         ["m365.mailbox.delegation.assignments"], {"viz": "timeseries"}),
        ("Delegation scan coverage (covered < total means a PARTIAL view)",
         ["m365.mailbox.delegation.mailboxes_covered",
          "m365.mailbox.delegation.mailboxes_total"],
         {"viz": "timeseries"}),
        ("Inbox rules (forwarding rules are a persistence mechanism)",
         ["m365.inbox_rules.rules"], {"viz": "timeseries"}),
        ("Inbox-rule scan coverage (covered < total means a PARTIAL view)",
         ["m365.inbox_rules.mailboxes_covered",
          "m365.inbox_rules.mailboxes_total"],
         {"viz": "timeseries"}),
    ]),
    ("SharePoint and OneDrive", [
        ("SharePoint tenant sharing posture", ["m365.sharepoint.sharing"],
         {"viz": "table", "w": 12, "h": 8}),
        ("Sharing domain allow/block lists",
         ["m365.sharepoint.sharing_allowed_domains",
          "m365.sharepoint.sharing_blocked_domains"],
         {"viz": "timeseries"}),
        ("SharePoint tenant switches",
         ["m365.sharepoint.external_resharing_enabled",
          "m365.sharepoint.legacy_auth_enabled",
          "m365.sharepoint.idle_session_signout_enabled",
          "m365.sharepoint.unmanaged_sync_restricted"],
         {"viz": "timeseries", "w": 24}),
        ("Storage limits",
         ["m365.sharepoint.site_storage_limit_mb",
          "m365.sharepoint.personal_site_storage_limit_mb"],
         {"viz": "timeseries"}),
        "m365.sharepoint.deleted_user_retention_days",
        "m365.storage.drives.total",
        ("Drive storage used vs total",
         ["m365.storage.used_bytes", "m365.storage.total_bytes"],
         {"viz": "timeseries"}),
    ]),
    ("Teams", [
        "m365.teams.total",
        "m365.teams.channels.total",
        "m365.teams.membership.total",
        "m365.teams.installed_apps.total",
        ("Teams governance gaps",
         ["m365.teams.ownerless.total", "m365.teams.with_guests.total"],
         {"viz": "timeseries"}),
    ]),
    ("Service health", [
        "m365.service_health.issues.total",
        "m365.service_health.services.total",
        ("Service health status ladder", ["m365.service_health.status"],
         {"viz": "table", "w": 24, "h": 8}),
        "m365.service_messages.total",
    ]),
    ("Collaboration activity (daily usage reports)", [
        # #362. Adoption and staleness, not events — the audit feeds cover
        # events. never_active is the interesting bucket: a licensed user who
        # has never touched the workload is a licence question.
        ("Users by workload and activity state",
         ["m365.collaboration_activity.users"], {"viz": "table", "w": 12, "h": 8}),
        ("Activity totals by workload and action",
         ["m365.collaboration_activity.actions"], {"viz": "table", "w": 12, "h": 8}),
        # External sharing gets its own panel rather than living inside the
        # actions table: it is the alertable one, and an operator should not
        # have to filter a table to find it.
        ("Files shared EXTERNALLY by workload",
         ["m365.collaboration_activity.shared_externally"], {"viz": "timeseries"}),
        "m365.collaboration_activity.users.deleted",
    ]),
    ("Mail flow (message trace — HIGH VOLUME, opt-in)", [
        "m365.message_trace.messages",
        "m365.message_trace.bytes",
    ]),
]

LOGS = [
    {"kind": "logs", "event": "m365.audit",
     "title": "Unified audit — which user, which operation",
     "desc": "user_key is the opaque classic UserKey; user_id is usually the UPN but "
             "carries sentinels too. Correlate the two M365 audit transports on user_id.",
     "w": 24, "h": 12},
    {"kind": "table", "event": "m365.audit",
     "title": "Top audited operations by workload",
     "by": ["workload", "operation"]},
    {"kind": "rate", "event": "m365.audit",
     "title": "Audit record rate by result status",
     "by": ["result_status"]},
    {"kind": "table", "event": "m365.message_trace",
     "title": "Message trace: top senders (HIGH VOLUME, opt-in)",
     "by": ["sender_address", "status"],
     "desc": "One record per message per recipient — the rate scales with traffic, not "
             "tenant size. Empty unless the collector is explicitly enabled."},
]
