"""Microsoft Purview — DLP, sensitivity/retention labels, eDiscovery."""

UID = "graph2otel-purview-compliance"
TITLE = "graph2otel: Purview data governance"
DESCRIPTION = (
    "Purview data loss prevention, sensitivity and retention labels, and eDiscovery "
    "cases, with the per-policy and per-label log twins. Generated by "
    "grafana/build_dashboard.py from spec/signal-catalog.json — edit "
    "grafana/boards/purview_compliance.py, not this JSON."
)
TAGS = ["graph2otel", "purview", "compliance", "generated"]
TENANT_METRIC = "purview_labels_count"

SECTIONS = [
    ("Data loss prevention", [
        "purview.dlp.policies",
        "purview.dlp.rules",
        "purview.dlp.policy_bindings",
        "purview.dlp.policy.last_changed_age",
    ]),
    ("Labels and retention", [
        "purview.labels.count",
        "purview.retention.labels.count",
        "purview.retention.event_types.count",
    ]),
    ("eDiscovery", [
        "purview.ediscovery.cases",
    ]),
]

LOGS = [
    {"kind": "logs", "event": "purview.sensitivity_label",
     "title": "Sensitivity labels — which label, what it applies to",
     "desc": "The metric counts labels by scope. This names each one, with its "
             "priority and description.",
     "w": 24, "h": 10},
    {"kind": "table", "event": "purview.dlp_policy",
     "title": "DLP policies by enforcement mode",
     "by": ["policy_name", "enforcement_mode"]},
    {"kind": "table", "event": "purview.retention_label",
     "title": "Retention labels by retention behaviour",
     "by": ["behavior_during_retention", "action_after_retention"]},
]
