"""graph2otel self-observability — is the exporter itself healthy?

# The one board the catalog cannot fully describe

Every other board is 100% catalog-driven. This one is not, and the reason is
structural rather than an oversight: ``internal/signalcapture`` captures what a
COLLECTOR PACKAGE's tests emit, so the goldens carry only the seven
``graph2otel.*`` metrics that collectors themselves emit. The rest of the
self-observability surface — scrape health, checkpoint persistence, export jobs,
the cardinality limiter, throttling, outbound HTTP — is emitted by the scheduler,
the transport and the telemetry package, none of which is a collector package
and none of which has a golden.

Those metrics are declared in ``grafana/selfobs_metrics.py`` (the ``SELF_OBS``
allow-list), by hand, as ``(otel name, unit, kind)`` triples copied from their
emit sites — shared with ``grafana/build_rules.py`` (#219) so the two
generators cannot each hand-declare their own copy and drift apart. Only the
triple is hand-kept: the Prometheus name is DERIVED by ``promname.prom_name``,
the same rule the Go catalog uses, pinned to it by a test over all 274
cataloged metrics. That is what keeps the derivation honest even where the
catalog cannot reach.

**These panels are NOT covered by the coverage gate** — the gate can only gate
what the catalog can see. Extending signalcapture to non-collector packages is
the fix, and it belongs with signalcapture, not here.
"""

from builder import RATE, TENANT_SEL
from selfobs_metrics import SELF_OBS

UID = "graph2otel-self-obs"
TITLE = "graph2otel / Self-Observability"
DESCRIPTION = (
    "Is graph2otel itself healthy: scrape success, duration and staleness per "
    "collector, checkpoint persistence, export-job outcomes, the cardinality limiter, "
    "Graph throttling and outbound HTTP. Generated by grafana/build_dashboard.py — "
    "edit grafana/boards/selfobs.py, not this JSON."
)
TAGS = ["graph2otel", "self-observability", "generated"]
TENANT_METRIC = "graph2otel_scrape_success_ratio"

# The seven graph2otel.* metrics that ARE cataloged, because collector packages
# emit them. These go through the normal catalog-driven path and ARE covered.
SECTIONS = [
    ("Blob ingest health and API drift (cataloged)", [
        ("Microsoft API drift — a response no longer matches what a collector expects",
         ["graph2otel.api.unexpected"], {"w": 24, "h": 8}),
        "graph2otel.blob.categories",
        "graph2otel.blob.endpoint_paths",
        "graph2otel.blob.event_age",
        ("Blob records: emitted as metrics vs gated",
         ["graph2otel.blob.metric_emitted", "graph2otel.blob.metric_gated"],
         {"viz": "timeseries"}),
        "graph2otel.logpipeline.self_excluded",
    ]),
]

# Prometheus names for the self-obs metrics no golden captures, read from the
# shared SELF_OBS allow-list (grafana/selfobs_metrics.py) rather than
# hand-declared here.
SCRAPE_SUCCESS = SELF_OBS["graph2otel.scrape.success"].prom
SCRAPE_DURATION = SELF_OBS["graph2otel.scrape.duration"].prom
SCRAPE_STALENESS = SELF_OBS["graph2otel.scrape.staleness"].prom
SCRAPE_BUDGET = SELF_OBS["graph2otel.scrape.budget"].prom
SCRAPE_ERRORS = SELF_OBS["graph2otel.scrape.errors"].prom
CHECKPOINT_ERRORS = SELF_OBS["graph2otel.checkpoint.persist.errors"].prom
BUILD_INFO = SELF_OBS["graph2otel.build_info"].prom
LICENSE_TIER = SELF_OBS["graph2otel.tenant.license_tier"].prom
EXPORT_JOBS = SELF_OBS["graph2otel.export.jobs"].prom
EXPORT_DURATION = SELF_OBS["graph2otel.export.duration_seconds"].prom
EXPORT_POLLS = SELF_OBS["graph2otel.export.poll_count"].prom
EXPORT_BYTES = SELF_OBS["graph2otel.export.bytes"].prom
SERIES_ACTIVE = SELF_OBS["graph2otel.series.active"].prom
SERIES_LIMIT = SELF_OBS["graph2otel.series.limit"].prom
SERIES_CLIPPED = SELF_OBS["graph2otel.series.clipped"].prom
THROTTLE_COUNT = SELF_OBS["graph2otel.throttle.count"].prom
THROTTLE_PCT = SELF_OBS["graph2otel.throttle.limit_percentage"].prom
HTTP_DURATION = SELF_OBS["graph2otel.http.client.request.duration"].prom
HTTP_4XX = SELF_OBS["graph2otel.graphclient.http_4xx"].prom
HTTP_5XX = SELF_OBS["graph2otel.graphclient.http_5xx"].prom

_SEL = "{" + TENANT_SEL + ', collector=~"$collector"}'
_T = "{" + TENANT_SEL + "}"


def extra(b):
    b.variable({
        "name": "collector", "label": "Collector", "type": "query",
        "datasource": {"type": "prometheus", "uid": "${datasource}"},
        "refresh": 2, "includeAll": True, "multi": True, "sort": 1,
        "current": {}, "options": [], "hide": 0,
        "query": {"qryType": 1,
                  "query": f'label_values({SCRAPE_SUCCESS}{{tenant_id=~"$tenant"}}, collector)',
                  "refId": "collector"},
        "definition": f'label_values({SCRAPE_SUCCESS}{{tenant_id=~"$tenant"}}, collector)',
    })
    b.row("Collector health (hand-declared — see the module docstring)")
    b.raw("Scrape success by collector", [f"{SCRAPE_SUCCESS}{_SEL}"],
          desc="1 when the last run completed without error, 0 otherwise (including a "
               "recovered panic). A green tick is not evidence of data: several "
               "collectors succeed on an empty collection by design.")
    b.raw("Scrape duration by collector", [f"{SCRAPE_DURATION}{_SEL}"], unit="s")
    b.raw("Scrape staleness (seconds since last SUCCESS)", [f"{SCRAPE_STALENESS}{_SEL}"],
          viz="table", unit="s",
          desc="Counts up from process start until the first success, so a collector "
               "that has never succeeded shows a growing value rather than no series.")
    b.raw("Scrape budget (duration / interval)", [f"{SCRAPE_BUDGET}{_SEL}"],
          desc="At or above 1 a scrape takes as long as its own poll interval — no "
               "headroom, risk of overrun.")
    b.raw("Scrape error rate by error type",
          [f"sum by (collector, error_type) (rate({SCRAPE_ERRORS}{_SEL}[{RATE}]))"])
    b.raw("Checkpoint persist error rate",
          [f"sum by (collector) (rate({CHECKPOINT_ERRORS}{_SEL}[{RATE}]))"],
          desc="The window succeeded but its high-water mark did not reach disk. The "
               "next tick still advances; the window is only re-polled after a restart.")

    b.row("Build and licensing")
    b.raw("Build info (what is deployed)", [f"{BUILD_INFO}{_T}"], viz="table", w=12, h=6)
    b.raw("Detected license tier by tenant", [f"{LICENSE_TIER}{_T}"], viz="table", w=12, h=6)

    b.row("Export jobs (Intune report exports, M365 audit query)")
    b.raw("Export jobs by result",
          [f"sum by (report_name, result) (rate({EXPORT_JOBS}{_T}[{RATE}]))"], w=8)
    b.raw("Export job duration", [f"{EXPORT_DURATION}{_T}"], unit="s", w=8)
    b.raw("Export polls to terminal state", [f"{EXPORT_POLLS}{_T}"], w=8)
    b.raw("Downloaded export size", [f"{EXPORT_BYTES}{_T}"], unit="bytes", w=24, h=6)

    b.row("Cardinality limiter (#235)")
    b.raw("Active series by source metric",
          [f"topk(25, {SERIES_ACTIVE}{_T})"], viz="table", w=12, h=8,
          desc="Distinct series emitted per source metric AFTER limiting — the series "
               "actually billed.")
    b.raw("Series clipped, by mode",
          [f"sum by (metric_name, mode) ({SERIES_CLIPPED}{_T})"], w=12, h=8,
          desc="mode=folded were summed into the `other` bucket; mode=dropped were "
               "discarded because the metric is not additive and a synthetic aggregate "
               "would be worse than the loss.")
    b.raw("Configured per-metric series limit", [f"{SERIES_LIMIT}{_T}"], viz="stat",
          w=24, h=4)

    b.row("Graph throttling and outbound HTTP")
    b.raw("Throttle (429) rate by workload",
          [f"sum by (workload) (rate({THROTTLE_COUNT}{_T}[{RATE}]))"], w=8)
    b.raw("Graph-reported throttle budget consumed", [f"{THROTTLE_PCT}{_T}"],
          unit="percent", w=8,
          desc="From the x-ms-throttle-limit-percentage response header, which is not "
               "sent on every 429 or every workload — an absent series does NOT mean "
               "the budget is healthy.")
    b.raw("Outbound Graph request latency (p95)",
          [f"histogram_quantile(0.95, sum by (le) (rate({HTTP_DURATION}_bucket{_T}[{RATE}])))"],
          unit="s", w=8)
    b.raw("Outbound Graph 4xx / 5xx rate by workload",
          [f"sum by (workload) (rate({HTTP_4XX}{_T}[{RATE}]))",
           f"sum by (workload) (rate({HTTP_5XX}{_T}[{RATE}]))"],
          legends=["4xx {{workload}}", "5xx {{workload}}"], w=24, h=8)


LOGS = [
    {"kind": "logs", "event": "graph2otel.blob_category",
     "title": "Blob diagnostic categories — which container, mapped or not",
     "desc": "One record per diagnostic category found in the storage account, saying "
             "whether graph2otel has a mapper for it. An unmapped category is data "
             "arriving that nothing reads.",
     "w": 24, "h": 10},
]
