"""graph2otel self-observability — is the exporter itself healthy?

Every metric here comes from the generated signal catalog. Non-collector
emitters own dedicated signal goldens, so scrape health, transport clients,
export jobs and cardinality telemetry have the same name/shape/attribute drift
gate as domain collectors. Presentation remains hand-authored; signal authority
does not.
"""

from builder import RATE, TENANT_SEL
import catalog as catalog_mod

CAT = catalog_mod.load()
SELF_OBS = {
    name: metric for name, metric in CAT.metrics.items()
    if metric.domain == catalog_mod.SELF_OBS_DOMAIN
}

UID = "graph2otel-self-obs"
TITLE = "graph2otel / Self-Observability"
DESCRIPTION = (
    "Is graph2otel itself healthy: scrape and record outcomes, event lag, payload drift, "
    "checkpoint persistence, OTLP delivery, export-job outcomes, the cardinality limiter, Graph "
    "throttling and outbound HTTP. Generated by grafana/build_dashboard.py — "
    "edit grafana/boards/selfobs.py, not this JSON."
)
TAGS = ["graph2otel", "self-observability", "generated"]
TENANT_METRIC = SELF_OBS["graph2otel.collector.availability"].prom
# This board owns the complete cross-domain availability presentation below.
AVAILABILITY_PATTERN = None

SECTIONS = [
    ("Blob ingest health and API drift", [
        ("Microsoft API drift — a response no longer matches what a collector expects",
         ["graph2otel.api.unexpected"], {"w": 24, "h": 8}),
        "graph2otel.blob.categories",
        "graph2otel.blob.endpoint_paths",
        "graph2otel.blob.event_age",
        "graph2otel.blob.records_dropped",
        "graph2otel.blob.self_excluded",
        ("Blob records: emitted as metrics vs gated",
         ["graph2otel.blob.metric_emitted", "graph2otel.blob.metric_gated"],
         {"viz": "timeseries"}),
        "graph2otel.logpipeline.self_excluded",
    ]),
]

# Prometheus names are read from the generated catalog rather than typed here.
SCRAPE_SUCCESS = SELF_OBS["graph2otel.scrape.success"].prom
COLLECTOR_AVAILABILITY = SELF_OBS["graph2otel.collector.availability"].prom
SCRAPE_DURATION = SELF_OBS["graph2otel.scrape.duration"].prom
SCRAPE_STALENESS = SELF_OBS["graph2otel.scrape.staleness"].prom
SCRAPE_LAST = SELF_OBS["graph2otel.scrape.last_timestamp"].prom
SCRAPE_BUDGET = SELF_OBS["graph2otel.scrape.budget"].prom
SCRAPE_ERRORS = SELF_OBS["graph2otel.scrape.errors"].prom
SCRAPE_OUTCOMES = SELF_OBS["graph2otel.scrape.outcomes"].prom
RECORD_OUTCOMES = SELF_OBS["graph2otel.record.outcomes"].prom
EVENT_LAG = SELF_OBS["graph2otel.event.lag"].prom
TYPE_MISMATCHES = SELF_OBS["graph2otel.payload.type_mismatches"].prom
CHECKPOINT_ERRORS = SELF_OBS["graph2otel.checkpoint.persist.errors"].prom
BUILD_INFO = SELF_OBS["graph2otel.build_info"].prom
LICENSE_TIER = SELF_OBS["graph2otel.tenant.license_tier"].prom
EXPORT_JOBS = SELF_OBS["graph2otel.export.jobs"].prom
EXPORT_DURATION = SELF_OBS["graph2otel.export.duration_seconds"].prom
EXPORT_POLLS = SELF_OBS["graph2otel.export.poll_count"].prom
EXPORT_BYTES = SELF_OBS["graph2otel.export.bytes"].prom
SERIES_ACTIVE = SELF_OBS["graph2otel.series.active"].prom
SERIES_LIMIT = SELF_OBS["graph2otel.series.limit"].prom
SERIES_CLIPPED = SELF_OBS["graph2otel.series.clipped"].prom
SERIES_TOTAL = SELF_OBS["graph2otel.series.total"].prom
THROTTLE_COUNT = SELF_OBS["graph2otel.throttle.count"].prom
THROTTLE_PCT = SELF_OBS["graph2otel.throttle.limit_percentage"].prom
HTTP_DURATION = SELF_OBS["graph2otel.http.client.request.duration"].prom
HTTP_4XX = SELF_OBS["graph2otel.graphclient.http_4xx"].prom
HTTP_5XX = SELF_OBS["graph2otel.graphclient.http_5xx"].prom
EXO_DURATION = SELF_OBS["graph2otel.exo.http.client.request.duration"].prom
EXO_4XX = SELF_OBS["graph2otel.exo.http_4xx"].prom
EXO_5XX = SELF_OBS["graph2otel.exo.http_5xx"].prom
EXO_THROTTLE = SELF_OBS["graph2otel.exo.throttle.count"].prom
HUNT_DURATION = SELF_OBS["graph2otel.hunt.http.client.request.duration"].prom
HUNT_4XX = SELF_OBS["graph2otel.hunt.http_4xx"].prom
HUNT_5XX = SELF_OBS["graph2otel.hunt.http_5xx"].prom
HUNT_THROTTLE = SELF_OBS["graph2otel.hunt.throttle.count"].prom
MDCA_DURATION = SELF_OBS["graph2otel.mdca.http.client.request.duration"].prom
MDCA_4XX = SELF_OBS["graph2otel.mdca.http_4xx"].prom
MDCA_5XX = SELF_OBS["graph2otel.mdca.http_5xx"].prom
MDCA_THROTTLE = SELF_OBS["graph2otel.mdca.throttle.count"].prom
O365_DURATION = SELF_OBS["graph2otel.o365activity.http.client.request.duration"].prom
O365_4XX = SELF_OBS["graph2otel.o365activity.http_4xx"].prom
O365_5XX = SELF_OBS["graph2otel.o365activity.http_5xx"].prom
O365_THROTTLE = SELF_OBS["graph2otel.o365activity.throttle.count"].prom
DELIVERY_DEGRADED = SELF_OBS["graph2otel.otlp.delivery.degraded"].prom
DELIVERY_ATTEMPTS = SELF_OBS["graph2otel.otlp.delivery.export_attempts"].prom
DELIVERY_SUCCESSES = SELF_OBS["graph2otel.otlp.delivery.export_successes"].prom
DELIVERY_FAILURES = SELF_OBS["graph2otel.otlp.delivery.export_failures"].prom
DELIVERY_FLUSH_FAILURES = SELF_OBS[
    "graph2otel.otlp.delivery.force_flush_failures"
].prom
DELIVERY_SHUTDOWN_FAILURES = SELF_OBS[
    "graph2otel.otlp.delivery.shutdown_failures"
].prom
INGEST_SOURCE_RECORDS = SELF_OBS["graph2otel.ingest.source_records"].prom
INGEST_EMITTED_POINTS = SELF_OBS["graph2otel.ingest.emitted_points"].prom
OTLP_TRANSMITTED_PAYLOAD_BYTES = SELF_OBS[
    "graph2otel.otlp.transmitted_payload.bytes"
].prom
OTLP_RETRY_ATTEMPTS = SELF_OBS["graph2otel.otlp.retry_attempts"].prom
INGEST_COST_PROJECTED = SELF_OBS["graph2otel.ingest.cost.projected"].prom

_SEL = "{" + TENANT_SEL + ', collector=~"$collector"}'
_AVAIL_SEL = '{tenant_id=~"$tenant",collector=~"$collector"}'
_T = "{" + TENANT_SEL + "}"


def extra(b):
    b.variable({
        "name": "collector", "label": "Collector", "type": "query",
        "datasource": {"type": "prometheus", "uid": "${datasource}"},
        "refresh": 2, "includeAll": True, "multi": True, "sort": 1,
        "current": {}, "options": [], "hide": 0,
        "query": {"qryType": 1,
                  "query": f'label_values({COLLECTOR_AVAILABILITY}{{tenant_id=~"$tenant"}}, collector)',
                  "refId": "collector"},
        "definition": f'label_values({COLLECTOR_AVAILABILITY}{{tenant_id=~"$tenant"}}, collector)',
    })
    b.row("OTLP delivery (process-wide)")
    b.raw(
        "Current exporter degradation by signal",
        [f"max by (signal) ({DELIVERY_DEGRADED})"],
        viz="table", w=24, h=6,
        desc="Current process-local exporter callback state for metrics and logs. "
             "1 means the latest failure has not been cleared by a later successful "
             "export; 0 means it has. This does not change liveness or readiness.",
    )
    b.raw(
        "Exporter callback rates by signal",
        [
            f"sum by (signal) (rate({DELIVERY_ATTEMPTS}[{RATE}]))",
            f"sum by (signal) (rate({DELIVERY_SUCCESSES}[{RATE}]))",
            f"sum by (signal) (rate({DELIVERY_FAILURES}[{RATE}]))",
        ],
        legends=[
            "attempts {{signal}}",
            "accepted {{signal}}",
            "failed {{signal}}",
        ],
        w=24, h=8,
        desc="Exporter callback attempts, accepted callbacks, and failures for the "
             "metrics and logs pipelines independently. These overlapping rates are "
             "deliberately unstacked; attempts equal successes plus failures.",
    )
    b.raw(
        "Force-flush failure rate by signal",
        [f"sum by (signal) (rate({DELIVERY_FLUSH_FAILURES}[{RATE}]))"],
        legends=["{{signal}}"],
        w=12, h=6,
        desc="Failed force-flush callbacks by signal. A later successful export clears "
             "degradation; an empty successful flush does not claim payload acceptance.",
    )
    b.raw(
        "Shutdown failure total by signal",
        [f"sum by (signal) ({DELIVERY_SHUTDOWN_FAILURES})"],
        legends=["{{signal}}"],
        w=12, h=6,
        desc="Process-lifetime failed shutdown callbacks by signal. Shutdown failure "
             "does not alter dependency-free liveness or readiness semantics.",
    )
    b.raw(
        "Exact transmitted OTLP payload rate by signal",
        [f"sum by (signal) (rate({OTLP_TRANSMITTED_PAYLOAD_BYTES}[{RATE}]))"],
        legends=["{{signal}}"],
        unit="Bps", w=12, h=6,
        desc="Exact post-compression OTLP payload bytes accepted by the client "
             "transport on each send. This process-wide measurement excludes HTTP/gRPC "
             "framing, TLS, TCP/IP and kernel retransmission.",
    )
    b.raw(
        "Exact exporter retry rate by signal",
        [f"sum by (signal) (rate({OTLP_RETRY_ATTEMPTS}[{RATE}]))"],
        legends=["{{signal}}"],
        w=12, h=6,
        desc="Exact second-and-later exporter retry-loop attempts for metrics and logs. "
             "Redirects and transparent connection retries are excluded.",
    )
    b.row("Collector availability")
    availability = f"{COLLECTOR_AVAILABILITY}{_AVAIL_SEL}"
    b.raw(
        "Current collector availability",
        [f"max by (tenant_id, collector, collector_transport, state, reason) ({availability})"],
        viz="table", w=24, h=12,
        desc="One current value-1 row per tenant and logical collector. collector_transport is "
             "the resolved collector transport, not the log-record ingest_transport.",
    )
    b.raw(
        "Collector availability by state",
        [f"count by (tenant_id, state) ({availability})"],
        viz="bargauge", w=12, h=7,
        desc="Current logical-collector counts by bounded availability state. This is a "
             "snapshot, not a scrape-success or record-throughput count.",
    )
    b.raw(
        "Intentional collector absence",
        [f'max by (tenant_id, collector, collector_transport, state, reason) '
         f'({COLLECTOR_AVAILABILITY}{{{TENANT_SEL}, collector=~"$collector", state=~"disabled|covered"}})'],
        viz="table", w=12, h=7,
        desc="Disabled and covered collectors are intentional absence, shown separately "
             "from runtime or startup failures.",
    )
    b.raw(
        "Collector availability failures",
        [f'max by (tenant_id, collector, collector_transport, state, reason) '
         f'({COLLECTOR_AVAILABILITY}{{{TENANT_SEL}, collector=~"$collector", '
         f'state=~"degraded|failed|startup_failed"}})',
         f'max by (tenant_id, collector, collector_transport, state, reason) '
         f'({COLLECTOR_AVAILABILITY}{{{TENANT_SEL}, collector=~"$collector", '
         f'state="blocked", reason="permission_denied"}})'],
        viz="table", w=12, h=7,
        desc="Current permission-denied blocks, degraded runs, failed runs, and startup failures. "
             "This is deliberately separate from configured absence and subscription limitations.",
    )
    b.raw(
        "Subscription and capability limitations",
        [f'max by (tenant_id, collector, collector_transport, state, reason) '
         f'({COLLECTOR_AVAILABILITY}{{{TENANT_SEL}, collector=~"$collector", '
         f'state="limited", reason="partial_license"}})',
         f'max by (tenant_id, collector, collector_transport, state, reason) '
         f'({COLLECTOR_AVAILABILITY}{{{TENANT_SEL}, collector=~"$collector", '
         f'state="blocked", reason="license_unavailable"}})'],
        viz="table", w=12, h=7,
        desc="This non-failure view shows subscription and capability limitations: a partial license can "
             "keep a collector running with a reduced capability set, while an unavailable license blocks it. "
             "Exact omitted capabilities are available from the admin status, not labels.",
    )
    b.row("Collector health (generated signal catalog)")
    b.raw("Scrape success by collector", [f"{SCRAPE_SUCCESS}{_SEL}"],
          desc="1 when the last reconciled run was empty or successful; 0 when it was "
               "partial or failed (including a recovered panic). A green tick is not "
               "evidence of data: several collectors succeed on an empty collection "
               "by design.")
    b.raw("Scrape duration by collector", [f"{SCRAPE_DURATION}{_SEL}"], unit="s")
    b.raw("Scrape staleness (seconds since last healthy result)",
          [f"{SCRAPE_STALENESS}{_SEL}"],
          viz="table", unit="s",
          desc="Counts up from process start until the first empty or successful result, "
               "so a collector that has never been healthy shows a growing value rather "
               "than no series.")
    b.raw("Age of the latest completed scrape",
          [f"time() - {SCRAPE_LAST}{_SEL}"], unit="s",
          desc="Wall-clock age of the latest completed run, whether it succeeded or failed.")
    b.raw("Scrape budget (duration / interval)", [f"{SCRAPE_BUDGET}{_SEL}"],
          desc="At or above 1 a scrape takes as long as its own poll interval — no "
               "headroom, risk of overrun.")
    b.raw("Scrape error rate by error type",
          [f"sum by (collector, error_type) (rate({SCRAPE_ERRORS}{_SEL}[{RATE}]))"])
    b.raw("Checkpoint persist error rate",
          [f"sum by (collector) (rate({CHECKPOINT_ERRORS}{_SEL}[{RATE}]))"],
          desc="The window succeeded but its high-water mark did not reach disk. The "
               "next tick still advances; the window is only re-polled after a restart.")

    b.row("Record outcome accounting")
    b.raw("Collector runs by reconciled result",
          [f"sum by (tenant_id, collector, ingest_transport, result) "
           f"(rate({SCRAPE_OUTCOMES}{_SEL}[{RATE}]))"],
          legends=["{{tenant_id}} {{collector}} {{ingest_transport}} {{result}}"],
          desc="Separates healthy-empty polls from successful data-bearing polls and "
               "from partial or failed runs.")
    b.raw(
        "Source-record rate by outcome",
        [f"sum by (tenant_id, collector, ingest_transport, outcome) "
         f"(rate({RECORD_OUTCOMES}{_SEL}[{RATE}]))"],
        legends=["{{tenant_id}} {{collector}} {{ingest_transport}} {{outcome}}"],
        desc="One source row counts once at each lifecycle boundary; fetched, mapped, "
             "and terminal outcomes overlap and are deliberately unstacked. This is "
             "not the number of OTEL metric points or log records.",
    )
    b.raw(
        "Dropped / errored source records",
        [f"sum by (tenant_id, collector, ingest_transport, outcome) "
         f"(rate({RECORD_OUTCOMES}"
         f'{{{TENANT_SEL}, collector=~"$collector", outcome=~"dropped|errored"}}'
         f"[{RATE}]))"],
        legends=["{{tenant_id}} {{collector}} {{ingest_transport}} {{outcome}}"],
        desc="Any nonzero value is record loss. `dropped` is a deliberate rejection "
             "such as a missing event timestamp; `errored` is decode or processing failure.",
    )
    b.raw(
        "Source-event lag at emission",
        [
            f"histogram_quantile(0.50, sum by "
            f"(le, tenant_id, collector, ingest_transport) "
            f"(rate({EVENT_LAG}_bucket{_SEL}[{RATE}])))",
            f"histogram_quantile(0.95, sum by "
            f"(le, tenant_id, collector, ingest_transport) "
            f"(rate({EVENT_LAG}_bucket{_SEL}[{RATE}])))",
        ],
        unit="s",
        legends=["p50 {{tenant_id}} {{collector}} {{ingest_transport}}",
                 "p95 {{tenant_id}} {{collector}} {{ingest_transport}}"],
        desc="Source timestamp to graph2otel emission. It does not measure backend "
             "acceptance or OTLP delivery latency.",
    )
    b.raw(
        "Payload type mismatches",
        [f"sum by (tenant_id, collector, ingest_transport, field, expected_type, "
         f"actual_type) "
         f"(rate({TYPE_MISMATCHES}{_SEL}[{RATE}]))"],
        viz="table",
        desc="Report-only payload drift. Labels contain only source-controlled field "
             "names and closed JSON types, never field values.",
    )

    b.row("Ingest volume and estimated cost")
    b.raw(
        "Exact source-record rate by collector and traffic class",
        [f"sum by (tenant_id, collector, ingest_transport, traffic_class) "
         f"(rate({INGEST_SOURCE_RECORDS}{_SEL}[{RATE}]))"],
        legends=[
            "{{tenant_id}} {{collector}} {{ingest_transport}} {{traffic_class}}"
        ],
        w=12, h=7,
        desc="Exact logical source records fetched by completed collector runs. This "
             "traffic-class view comes from the same immutable snapshot as "
             "record.outcomes{outcome=\"fetched\"}. Normal runtime emits steady_state "
             "and cold_start_backfill; manual_replay is reserved and not emitted here.",
    )
    b.raw(
        "Exact emitted-point rate by collector, signal and traffic class",
        [f"sum by (tenant_id, collector, ingest_transport, signal, traffic_class) "
         f"(rate({INGEST_EMITTED_POINTS}{_SEL}[{RATE}]))"],
        legends=[
            "{{tenant_id}} {{collector}} {{ingest_transport}} {{signal}} "
            "{{traffic_class}}"
        ],
        w=12, h=7,
        desc="Exact metric and log points after the central limiter and handed to the "
             "OpenTelemetry SDK. This is not backend acceptance or retention.",
    )
    b.raw(
        "Estimated projected collector cost (configured period)",
        [f"max by (tenant_id, collector, ingest_transport, currency, price_version, "
         f"attribution) ({INGEST_COST_PROJECTED}"
         f'{{{TENANT_SEL}, collector=~"$collector", attribution="estimated"}})'],
        legends=[
            "{{tenant_id}} {{collector}} {{ingest_transport}} {{currency}} "
            "{{price_version}} {{attribution}}"
        ],
        viz="table", w=24, h=8,
        desc="Estimate, not invoice. Present only when cost.enabled is true, using the "
             "operator-supplied rates and configured projection period. This projects "
             "recurring steady_state rows from cumulative process-lifetime observations; "
             "exceptional interval cost remains in the admin view. Logical record and "
             "point components are exact; the collector payload-byte allocation is "
             "estimated. A configured budget is display-only and never changes "
             "collector behavior.",
    )

    b.row("Build and licensing")
    b.raw("Build info (process-wide)", [BUILD_INFO], viz="table", w=12, h=6,
          desc="One series for the graph2otel process. Tenant selection does not apply: "
               "duplicating build identity per tenant would create misleading copies of "
               "the same process fact.")
    b.raw("Detected license tier by tenant", [f"{LICENSE_TIER}{_T}"], viz="table", w=12, h=6)

    b.row("Export jobs (Intune report exports, M365 audit query)")
    b.raw("Export jobs by result",
          [f"sum by (report_name, result) (rate({EXPORT_JOBS}{_T}[{RATE}]))"], w=8)
    b.raw("Export job duration", [f"{EXPORT_DURATION}{_T}"], unit="s", w=8)
    b.raw("Export polls to terminal state", [f"{EXPORT_POLLS}{_T}"], w=8)
    b.raw("Downloaded export size", [f"{EXPORT_BYTES}{_T}"], unit="bytes", w=24, h=6)

    b.row("Cardinality limiter (#235)")
    b.raw("Active series by source metric (process-wide)",
          [f"topk(25, {SERIES_ACTIVE})"], viz="table", w=12, h=8,
          desc="Distinct series emitted per source metric across the shared process AFTER "
               "limiting — the series actually billed. Tenant selection does not apply.")
    b.raw("Series clipped, by mode (process-wide)",
          [f"sum by (metric_name, mode) ({SERIES_CLIPPED})"], w=12, h=8,
          desc="mode=folded were summed into the `other` bucket; mode=dropped were "
               "discarded because the metric is not additive and a synthetic aggregate "
               "would be worse than the loss. Counts cover the shared process; tenant "
               "selection does not apply.")
    b.raw("Total active series (process-wide)", [SERIES_TOTAL], viz="stat",
          w=12, h=4,
          desc="Total distinct active series across the shared process during the last "
               "export interval. Tenant selection does not apply.")
    b.raw("Configured per-metric series limit (process-wide)", [SERIES_LIMIT], viz="stat",
          w=12, h=4,
          desc="One process-wide cardinality policy. Tenant selection does not apply.")

    b.row("Graph throttling and outbound HTTP")
    b.raw("Throttle (429) rate by workload",
          [f"sum by (workload) (rate({THROTTLE_COUNT}{_T}[{RATE}]))"], w=8)
    b.raw("Graph-reported throttle budget consumed", [f"{THROTTLE_PCT}{_T}"],
          unit="percent", w=8,
          desc="From the x-ms-throttle-limit-percentage response header, which is not "
               "sent on every 429 or every workload — an absent series does NOT mean "
               "the budget is healthy.")
    b.raw("Outbound Graph request latency (p95)",
          [f"histogram_quantile(0.95, sum by (le) (rate({HTTP_DURATION}_bucket{_T}[{RATE}])))"],
          unit="s", w=8)
    b.raw("Outbound Graph 4xx / 5xx rate by workload",
          [f"sum by (workload) (rate({HTTP_4XX}{_T}[{RATE}]))",
           f"sum by (workload) (rate({HTTP_5XX}{_T}[{RATE}]))"],
          legends=["4xx {{workload}}", "5xx {{workload}}"], w=24, h=8)

    b.row("Non-Graph transport HTTP")
    for title, duration, errors4, errors5, throttle in [
        ("Exchange Online", EXO_DURATION, EXO_4XX, EXO_5XX, EXO_THROTTLE),
        ("Advanced hunting", HUNT_DURATION, HUNT_4XX, HUNT_5XX, HUNT_THROTTLE),
        ("MDCA", MDCA_DURATION, MDCA_4XX, MDCA_5XX, MDCA_THROTTLE),
        ("O365 Activity", O365_DURATION, O365_4XX, O365_5XX, O365_THROTTLE),
    ]:
        b.raw(f"{title} request latency (p95)",
              [f"histogram_quantile(0.95, sum by (le) "
               f"(rate({duration}_bucket{_T}[{RATE}])))"],
              unit="s", w=12, h=7)
        b.raw(f"{title} errors and throttling",
              [f"sum(rate({errors4}{_T}[{RATE}]))",
               f"sum(rate({errors5}{_T}[{RATE}]))",
               f"sum(rate({throttle}{_T}[{RATE}]))"],
              legends=["4xx", "5xx", "429 throttle"], w=12, h=7)


LOGS = [
    {"kind": "logs", "event": "graph2otel.blob_category",
     "title": "Blob diagnostic categories — which container, mapped or not",
     "desc": "One record per diagnostic category found in the storage account, saying "
             "whether graph2otel has a mapper for it. An unmapped category is data "
             "arriving that nothing reads.",
     "w": 24, "h": 10},
]
