"""Loader for spec/signal-catalog.json — the emitted-signal catalog (#218).

The catalog is generated by ``internal/signalcatalog`` from every collector
package's committed ``testdata/signals.json`` golden, which in turn is captured
from what the tests actually EMIT. Nothing here parses Go source, and nothing
here is hand-maintained: a new collector's golden is written by
``scripts/regen-generated.sh`` and this file picks it up with no human step.

That is the property the coverage gate rests on. A catalog somebody has to
remember to update would go stale exactly where it matters — on the collector
that just landed — and the gate would report coverage it does not have.
"""

from __future__ import annotations

import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
CATALOGUE = os.path.join(REPO, "spec", "signal-catalog.json")

# The self-observability namespace. Every other namespace is tenant domain data.
SELF_OBS_DOMAIN = "graph2otel"


class Metric:
    """One cataloged metric: what it is called, and what may be done with it."""

    __slots__ = ("name", "prom", "unit", "kind", "additive", "domain", "keys", "packages")

    def __init__(self, raw: dict):
        self.name = raw["name"]
        self.prom = raw["prometheus_name"]
        self.unit = raw["unit"]
        self.kind = raw["kind"]
        self.additive = raw["additive"]
        self.domain = raw["domain"]
        self.keys = list(raw["attr_keys"])
        self.packages = list(raw["packages"])

    def __repr__(self):  # pragma: no cover - debugging aid
        return f"Metric({self.name!r})"


class LogEvent:
    """One cataloged log event name and the union of its attribute keys."""

    __slots__ = ("event", "domain", "keys", "packages")

    def __init__(self, raw: dict):
        self.event = raw["event_name"]
        self.domain = raw["domain"]
        self.keys = list(raw["attr_keys"])
        self.packages = list(raw["packages"])

    def __repr__(self):  # pragma: no cover - debugging aid
        return f"LogEvent({self.event!r})"


class Catalog:
    def __init__(self, raw: dict):
        self.package_count = raw["package_count"]
        self.domains = list(raw["domains"])
        self.metrics = {m["name"]: Metric(m) for m in raw["metrics"]}
        self.logs = {log["event_name"]: LogEvent(log) for log in raw["logs"]}
        self._matchers = _build_matchers(self.metrics.values())

    def metric(self, name: str) -> Metric:
        try:
            return self.metrics[name]
        except KeyError:
            raise KeyError(
                f"{name!r} is not in {os.path.relpath(CATALOGUE, REPO)}. Either it is misspelled, "
                f"or the collector that emits it no longer does — regenerate with "
                f"`scripts/regen-generated.sh catalog` and fix the board module."
            ) from None

    def log(self, event: str) -> LogEvent:
        try:
            return self.logs[event]
        except KeyError:
            raise KeyError(
                f"{event!r} is not a cataloged log event. Check "
                f"{os.path.relpath(CATALOGUE, REPO)} for the exact event name."
            ) from None

    def metrics_referenced_by(self, expr: str) -> set:
        """Return every catalog metric whose Prometheus name appears in expr.

        This is what makes the coverage gate an observation rather than
        bookkeeping: a panel is credited only when the metric's name is really in
        the query text it ships, so a declaration that never made it into an
        expression cannot claim coverage.

        Matching is right-boundary anchored, because a plain substring test would
        let ``intune_devices_count`` be "covered" by a longer name that merely
        starts with it. Histograms additionally match their ``_bucket`` /
        ``_sum`` / ``_count`` series, which is the only form they are ever
        queried through — the bare base name never appears in a working query.
        """
        found = set()
        for name, rx in self._matchers:
            if rx.search(expr):
                found.add(name)
        return found


def _build_matchers(metrics) -> list:
    out = []
    for m in metrics:
        tail = r"(?:_bucket|_sum|_count)?" if m.kind == "histogram" else ""
        out.append((m.name, re.compile(re.escape(m.prom) + tail + r"(?![a-zA-Z0-9_])")))
    return out


def load(path: str = CATALOGUE) -> Catalog:
    with open(path) as f:
        return Catalog(json.load(f))
