package semconv

// Attribute keys used only by entra.* collectors.
const (
	AttrActivityDisplayName               = "activity_display_name"
	AttrAgentDisplayName                  = "agent_display_name"
	AttrAgentId                           = "agent_id"
	AttrAgreement                         = "agreement"
	AttrAlertCount                        = "alert_count"
	AttrAlertIds                          = "alert_ids"
	AttrApiVersion                        = "api_version"
	AttrAppDisplayName                    = "app_display_name"
	AttrAppObjectId                       = "app_object_id"
	AttrAppRole                           = "app_role"
	AttrAppRoleId                         = "app_role_id"
	AttrAssignedTo                        = "assigned_to"
	AttrAssignmentType                    = "assignment_type"
	AttrAuthenticationType                = "authentication_type"
	AttrBlueprintId                       = "blueprint_id"
	AttrCallerIpAddress                   = "caller_ip_address"
	AttrChangeId                          = "change_id"
	AttrClassification                    = "classification"
	AttrClientAppUsed                     = "client_app_used"
	AttrClientId                          = "client_id"
	AttrClientRequestId                   = "client_request_id"
	AttrConditionalAccessStatus           = "conditional_access_status"
	AttrConflictingValue                  = "conflicting_value"
	AttrConsentType                       = "consent_type"
	AttrContextId                         = "context_id"
	AttrCreatedDateTime                   = "created_date_time"
	AttrCreatedTime                       = "created_time"
	AttrCredentialDisplayName             = "credential_display_name"
	AttrCredentialOrigin                  = "credential_origin"
	AttrCredentialType                    = "credential_type"
	AttrCustomKeyIdentifier               = "custom_key_identifier"
	AttrCustomTags                        = "custom_tags"
	AttrCycleId                           = "cycle_id"
	AttrDetectionSource                   = "detection_source"
	AttrDetectionTimingType               = "detection_timing_type"
	AttrDetermination                     = "determination"
	AttrDurationMs                        = "duration_ms"
	AttrEndDateTime                       = "end_date_time"
	AttrEvidenceCount                     = "evidence_count"
	AttrGrantedScope                      = "granted_scope"
	AttrGroupType                         = "group_type"
	AttrIdentityProvider                  = "identity_provider"
	AttrIdentityType                      = "identity_type"
	AttrIncidentId                        = "incident_id"
	AttrInitiatorAppDisplayName           = "initiator_app_display_name"
	AttrInitiatorAppId                    = "initiator_app_id"
	AttrInitiatorServicePrincipalId       = "initiator_service_principal_id"
	AttrInitiatorUserId                   = "initiator_user_id"
	AttrInitiatorUserPrincipalName        = "initiator_user_principal_name"
	AttrIpAddress                         = "ip_address"
	AttrIsAdmin                           = "is_admin"
	AttrIsAdminManaged                    = "is_admin_managed"
	AttrIsDefault                         = "is_default"
	AttrIsEnabled                         = "is_enabled"
	AttrIsInitial                         = "is_initial"
	AttrIsProcessing                      = "is_processing"
	AttrIsReplay                          = "is_replay"
	AttrIsRoot                            = "is_root"
	AttrIsTrusted                         = "is_trusted"
	AttrIsVerified                        = "is_verified"
	AttrJobId                             = "job_id"
	AttrKeyId                             = "key_id"
	AttrKeyType                           = "key_type"
	AttrLastNonInteractiveSignInDateTime  = "last_non_interactive_sign_in_date_time"
	AttrLastNonInteractiveSignInRequestId = "last_non_interactive_sign_in_request_id"
	AttrLastSignInDateTime                = "last_sign_in_date_time"
	AttrLastSignInRequestId               = "last_sign_in_request_id"
	AttrLastSuccessfulSignInDateTime      = "last_successful_sign_in_date_time"
	AttrLastSuccessfulSignInRequestId     = "last_successful_sign_in_request_id"
	AttrLastUpdateTime                    = "last_update_time"
	AttrLastUpdated                       = "last_updated"
	AttrLocation                          = "location"
	AttrLocationCity                      = "location_city"
	AttrLocationCountryOrRegion           = "location_country_or_region"
	AttrLocationLatitude                  = "location_latitude"
	AttrLocationLongitude                 = "location_longitude"
	AttrLocationState                     = "location_state"
	AttrLoggedByService                   = "logged_by_service"
	AttrMailEnabled                       = "mail_enabled"
	AttrMembershipType                    = "membership_type"
	AttrMethod                            = "method"
	AttrMethodsRegistered                 = "methods_registered"
	AttrMfaCapable                        = "mfa_capable"
	AttrMfaRegistered                     = "mfa_registered"
	AttrMitreTechniques                   = "mitre_techniques"
	AttrNearPurge                         = "near_purge"
	AttrObjectType                        = "object_type"
	AttrOccurredDateTime                  = "occurred_date_time"
	AttrOperationId                       = "operation_id"
	AttrOperationType                     = "operation_type"
	AttrOwnerType                         = "owner_type"
	AttrPasswordlessCapable               = "passwordless_capable"
	AttrPermanent                         = "permanent"
	AttrPrincipalAppId                    = "principal_app_id"
	AttrPrincipalDisplayName              = "principal_display_name"
	AttrPrincipalId                       = "principal_id"
	AttrPrincipalType                     = "principal_type"
	AttrPrincipalUserPrincipalName        = "principal_user_principal_name"
	AttrPriorityScore                     = "priority_score"
	AttrPrivilege                         = "privilege"
	AttrPropertyCausingError              = "property_causing_error"
	AttrProviderAlertId                   = "provider_alert_id"
	AttrProvisioningAction                = "provisioning_action"
	AttrRecommendation                    = "recommendation"
	AttrRequestId                         = "request_id"
	AttrNormalizedPath                    = "normalized_path"
	AttrRequestMethod                     = "request_method"
	AttrRequestUri                        = "request_uri"
	AttrResourceDisplayName               = "resource_display_name"
	AttrResourceId                        = "resource_id"
	AttrResourceLabel                     = "resource_label"
	AttrResponseSizeBytes                 = "response_size_bytes"
	AttrResponseStatusClass               = "response_status_class"
	AttrResponseStatusCode                = "response_status_code"
	AttrResult                            = "result"
	AttrResultDescription                 = "result_description"
	AttrResultReason                      = "result_reason"
	AttrResultStatusCode                  = "result_status_code"
	AttrRiskDetail                        = "risk_detail"
	AttrRiskEventType                     = "risk_event_type"
	AttrRiskEvidence                      = "risk_evidence"
	AttrRiskLastUpdated                   = "risk_last_updated"
	AttrRiskLevel                         = "risk_level"
	AttrRiskLevelDuringSignIn             = "risk_level_during_sign_in"
	AttrRiskState                         = "risk_state"
	AttrRoleId                            = "role_id"
	AttrRoleName                          = "role_name"
	AttrRoles                             = "roles"
	AttrScope                             = "scope"
	AttrScopes                            = "scopes"
	AttrSecurityEnabled                   = "security_enabled"
	AttrServicePrincipalId                = "service_principal_id"
	AttrServicePrincipalName              = "service_principal_name"
	AttrServicePrincipalObjectId          = "service_principal_object_id"
	AttrServicePrincipalType              = "service_principal_type"
	AttrServiceSource                     = "service_source"
	AttrSignInActivityId                  = "sign_in_activity_id"
	AttrSignInEventTypes                  = "sign_in_event_types"
	AttrSku                               = "sku"
	AttrSourceIdentityDisplayName         = "source_identity_display_name"
	AttrSourceIdentityId                  = "source_identity_id"
	AttrSsprCapable                       = "sspr_capable"
	AttrSsprEnabled                       = "sspr_enabled"
	AttrSsprRegistered                    = "sspr_registered"
	AttrStatusErrorCode                   = "status_error_code"
	AttrStatusFailureReason               = "status_failure_reason"
	AttrStatusInfo                        = "status_info"
	AttrSupportedServices                 = "supported_services"
	AttrSystemPreferredAuthEnabled        = "system_preferred_auth_enabled"
	AttrSystemPreferredAuthMethods        = "system_preferred_auth_methods"
	AttrSystemTags                        = "system_tags"
	AttrTargetDisplayNames                = "target_display_names"
	AttrTargetIdentityDisplayName         = "target_identity_display_name"
	AttrTargetIdentityId                  = "target_identity_id"
	AttrTargetResourceCount               = "target_resource_count"
	AttrTenantType                        = "tenant_type"
	AttrThresholdDays                     = "threshold_days"
	AttrTitle                             = "title"
	AttrTokenIssuedAt                     = "token_issued_at"
	AttrTokenIssuerType                   = "token_issuer_type"
	AttrTrustType                         = "trust_type"
	AttrUserAgent                         = "user_agent"
	AttrUserPreferredSecondaryMethod      = "user_preferred_secondary_method"
	AttrUserPrincipalObjectId             = "user_principal_object_id"
	AttrWids                              = "wids"
	AttrWorkloadNamespace                 = "workload_namespace"
)

// Attribute keys passed indirectly — via a helper-func param (devices.boolSnapshot)
// or an axis-struct field (users) rather than as a literal at the emit site — so
// the #161 seed extraction, which scanned only direct setX/attrs[]/Attrs{} forms,
// missed them. Added in the migration so no bare attribute-key literal remains.
const (
	AttrAccountEnabled        = "account_enabled"
	AttrIsCompliant           = "is_compliant"
	AttrIsManaged             = "is_managed"
	AttrOnPremisesSyncEnabled = "on_premises_sync_enabled"
)

// Attribute keys for the entra.secure_score control twins (#243). The
// per-control state twin (entra.secure_score_control) carries the tenant's
// current per-control assessment from controlScores; the catalog twin
// (entra.secure_score_control_profile) carries the bounded control-profile
// metadata. Both are LOGS — per-control detail belongs on the twin, never a
// metric label (#114). control_category reuses AttrCategory; the profile's
// service/action_type reuse AttrService/AttrActionType; the profile id reuses
// AttrId.
const (
	// entra.application / federated-identity-credential (#244): app-ownership and
	// the trust-edge fields credential_expiry cannot see.
	AttrHasOwner            = "has_owner"
	AttrSignInAudience      = "sign_in_audience"
	AttrIssuerHost          = "issuer_host"
	AttrOwnerCount          = "owner_count"
	AttrOwnerPrincipalNames = "owner_principal_names"
	AttrCredentialName      = "credential_name"
	AttrAudiences           = "audiences"

	// entra.tenant_policy twin (#245): tenant posture fields the bounded 0/1
	// setting gauge cannot carry.
	AttrAllowInvitesFrom            = "allow_invites_from"
	AttrGuestUserRoleId             = "guest_user_role_id"
	AttrAdminConsentReviewerCount   = "admin_consent_reviewer_count"
	AttrAdminConsentRequestDuration = "admin_consent_request_duration_days"
	AttrPermissionGrantPolicies     = "permission_grant_policies"
	AttrAppPasswordCredsRestricted  = "app_password_credentials_restricted"

	// entra.pim_role_policy (#242): PIM role-activation policy requirements.
	AttrRoleDefinitionId          = "role_definition_id"
	AttrRequirement               = "requirement"
	AttrCaller                    = "caller"
	AttrIsOrganizationDefault     = "is_organization_default"
	AttrApprovalRequired          = "approval_required"
	AttrApprovalStageTimeoutDays  = "approval_stage_timeout_days"
	AttrActivationEnabledRules    = "activation_enabled_rules"
	AttrActivationMaxDuration     = "activation_max_duration"
	AttrAssignmentExpiryRequired  = "assignment_expiry_required"
	AttrAssignmentMaxDuration     = "assignment_max_duration"
	AttrEligibilityExpiryRequired = "eligibility_expiry_required"
	AttrEligibilityMaxDuration    = "eligibility_max_duration"
	AttrAuthContextEnabled        = "auth_context_enabled"
	AttrAuthContextClaim          = "auth_context_claim"

	AttrControlName          = "control_name"
	AttrScore                = "score"
	AttrScoreInPercentage    = "score_in_percentage"
	AttrImplementationStatus = "implementation_status"
	AttrControlCount         = "control_count"
	AttrControlTotal         = "control_total"
	AttrLastSynced           = "last_synced"
	AttrMaxScore             = "max_score"
	AttrTier                 = "tier"
	AttrRank                 = "rank"
	AttrThreats              = "threats"
	AttrActionUrl            = "action_url"
	AttrDeprecated           = "deprecated"
	AttrImplementationCost   = "implementation_cost"
	AttrUserImpact           = "user_impact"
	AttrScoreComparisonBasis = "basis"
)
