package semconv

// Attribute keys used only by defender.* collectors — the Microsoft Defender
// XDR advanced-hunting tables (#106). One key per advanced-hunting column, plus a
// few derived keys (geo_* promoted from an AlertEvidence Ip entity's Location).
// Shared keys these tables also emit (id, device_id, device_name, severity, ...
// failure_reason, ip_address) are reused from the other attrs_*.go files, never
// redeclared. Every key is a semconv.Attr* constant (Gate B); no value duplicates
// another constant (Gate A).
const (
	AttrAadDeviceId                                  = "aad_device_id"
	AttrAccountDomain                                = "account_domain"
	AttrAccountName                                  = "account_name"
	AttrAccountObjectId                              = "account_object_id"
	AttrAccountSid                                   = "account_sid"
	AttrAccountUpn                                   = "account_upn"
	AttrAction                                       = "action"
	AttrActionResult                                 = "action_result"
	AttrActionTrigger                                = "action_trigger"
	AttrActionType                                   = "action_type"
	AttrAdditionalFields                             = "additional_fields"
	AttrAlertId                                      = "alert_id"
	AttrAppGuardContainerId                          = "app_guard_container_id"
	AttrAppVersion                                   = "app_version"
	AttrApplication                                  = "application"
	AttrApplicationId                                = "application_id"
	AttrAssetValue                                   = "asset_value"
	AttrAttachmentCount                              = "attachment_count"
	AttrAttackTechniques                             = "attack_techniques"
	AttrAuthenticationDetails                        = "authentication_details"
	AttrAwsResourceName                              = "aws_resource_name"
	AttrAzureResourceId                              = "azure_resource_id"
	AttrAzureVmId                                    = "azure_vm_id"
	AttrAzureVmSubscriptionId                        = "azure_vm_subscription_id"
	AttrBulkComplaintLevel                           = "bulk_complaint_level"
	AttrCategories                                   = "categories"
	AttrCc                                           = "cc"
	AttrClientVersion                                = "client_version"
	AttrCloudPlatform                                = "cloud_platform"
	AttrCloudPlatforms                               = "cloud_platforms"
	AttrCloudResource                                = "cloud_resource"
	AttrConfidenceLevel                              = "confidence_level"
	AttrConnectivityType                             = "connectivity_type"
	AttrConnectors                                   = "connectors"
	AttrContext                                      = "context"
	AttrCreatedProcessSessionId                      = "created_process_session_id"
	AttrDeliveryAction                               = "delivery_action"
	AttrDeliveryLocation                             = "delivery_location"
	AttrDetectionMethods                             = "detection_methods"
	AttrDeviceCategory                               = "device_category"
	AttrDeviceDynamicTags                            = "device_dynamic_tags"
	AttrDeviceManualTags                             = "device_manual_tags"
	AttrDeviceSubtype                                = "device_subtype"
	AttrDirection                                    = "direction"
	AttrDistributionList                             = "distribution_list"
	AttrEmailAction                                  = "email_action"
	AttrEmailActionPolicy                            = "email_action_policy"
	AttrEmailActionPolicyGuid                        = "email_action_policy_guid"
	AttrEmailClusterId                               = "email_cluster_id"
	AttrEmailDirection                               = "email_direction"
	AttrEmailLanguage                                = "email_language"
	AttrEmailSize                                    = "email_size"
	AttrEmailSubject                                 = "email_subject"
	AttrEntityType                                   = "entity_type"
	AttrEvidenceDirection                            = "evidence_direction"
	AttrEvidenceRole                                 = "evidence_role"
	AttrExchangeTransportRule                        = "exchange_transport_rule"
	AttrExclusionReason                              = "exclusion_reason"
	AttrExpires                                      = "expires"
	AttrExposureLevel                                = "exposure_level"
	AttrFileName                                     = "file_name"
	AttrFileOriginIp                                 = "file_origin_ip"
	AttrFileOriginReferrerUrl                        = "file_origin_referrer_url"
	AttrFileOriginUrl                                = "file_origin_url"
	AttrFileSize                                     = "file_size"
	AttrFolderPath                                   = "folder_path"
	AttrForwardingInformation                        = "forwarding_information"
	AttrGcpFullResourceName                          = "gcp_full_resource_name"
	AttrGeoAsn                                       = "geo_asn"
	AttrGeoCity                                      = "geo_city"
	AttrGeoCountry                                   = "geo_country"
	AttrGeoState                                     = "geo_state"
	AttrHardwareUuid                                 = "hardware_uuid"
	AttrHostDeviceId                                 = "host_device_id"
	AttrInitiatingProcessAccountDomain               = "initiating_process_account_domain"
	AttrInitiatingProcessAccountName                 = "initiating_process_account_name"
	AttrInitiatingProcessAccountObjectId             = "initiating_process_account_object_id"
	AttrInitiatingProcessAccountSid                  = "initiating_process_account_sid"
	AttrInitiatingProcessAccountUpn                  = "initiating_process_account_upn"
	AttrInitiatingProcessCommandLine                 = "initiating_process_command_line"
	AttrInitiatingProcessCreationTime                = "initiating_process_creation_time"
	AttrInitiatingProcessFileName                    = "initiating_process_file_name"
	AttrInitiatingProcessFileSize                    = "initiating_process_file_size"
	AttrInitiatingProcessFolderPath                  = "initiating_process_folder_path"
	AttrInitiatingProcessId                          = "initiating_process_id"
	AttrInitiatingProcessIntegrityLevel              = "initiating_process_integrity_level"
	AttrInitiatingProcessLogonId                     = "initiating_process_logon_id"
	AttrInitiatingProcessMd5                         = "initiating_process_md5"
	AttrInitiatingProcessParentCreationTime          = "initiating_process_parent_creation_time"
	AttrInitiatingProcessParentFileName              = "initiating_process_parent_file_name"
	AttrInitiatingProcessParentId                    = "initiating_process_parent_id"
	AttrInitiatingProcessRemoteSessionDeviceName     = "initiating_process_remote_session_device_name"
	AttrInitiatingProcessRemoteSessionIp             = "initiating_process_remote_session_ip"
	AttrInitiatingProcessSessionId                   = "initiating_process_session_id"
	AttrInitiatingProcessSha1                        = "initiating_process_sha1"
	AttrInitiatingProcessSha256                      = "initiating_process_sha256"
	AttrInitiatingProcessSignatureStatus             = "initiating_process_signature_status"
	AttrInitiatingProcessSignerType                  = "initiating_process_signer_type"
	AttrInitiatingProcessTokenElevation              = "initiating_process_token_elevation"
	AttrInitiatingProcessUniqueId                    = "initiating_process_unique_id"
	AttrInitiatingProcessVersionInfoCompanyName      = "initiating_process_version_info_company_name"
	AttrInitiatingProcessVersionInfoFileDescription  = "initiating_process_version_info_file_description"
	AttrInitiatingProcessVersionInfoInternalFileName = "initiating_process_version_info_internal_file_name"
	AttrInitiatingProcessVersionInfoOriginalFileName = "initiating_process_version_info_original_file_name"
	AttrInitiatingProcessVersionInfoProductName      = "initiating_process_version_info_product_name"
	AttrInitiatingProcessVersionInfoProductVersion   = "initiating_process_version_info_product_version"
	AttrInternetMessageId                            = "internet_message_id"
	AttrIsAzureAdJoined                              = "is_azure_ad_joined"
	AttrIsAzureInfoProtectionApplied                 = "is_azure_info_protection_applied"
	AttrIsExcluded                                   = "is_excluded"
	AttrIsFirstContact                               = "is_first_contact"
	AttrIsInitiatingProcessRemoteSession             = "is_initiating_process_remote_session"
	AttrIsInternetFacing                             = "is_internet_facing"
	AttrIsLocalAdmin                                 = "is_local_admin"
	AttrIsProcessRemoteSession                       = "is_process_remote_session"
	AttrIsTransient                                  = "is_transient"
	AttrJoinType                                     = "join_type"
	AttrLocalIp                                      = "local_ip"
	AttrLocalIpType                                  = "local_ip_type"
	AttrLocalPort                                    = "local_port"
	AttrLoggedOnUsers                                = "logged_on_users"
	AttrLogonId                                      = "logon_id"
	AttrLogonType                                    = "logon_type"
	AttrMachineGroup                                 = "machine_group"
	AttrMd5                                          = "md5"
	AttrMergedDeviceIds                              = "merged_device_ids"
	AttrMergedToDeviceId                             = "merged_to_device_id"
	AttrMitigationStatus                             = "mitigation_status"
	AttrNetworkMessageId                             = "network_message_id"
	AttrOauthApplicationId                           = "oauth_application_id"
	AttrOnboardingStatus                             = "onboarding_status"
	AttrOrgLevelAction                               = "org_level_action"
	AttrOrgLevelPolicy                               = "org_level_policy"
	AttrOsArchitecture                               = "os_architecture"
	AttrOsBuild                                      = "os_build"
	AttrOsBuildRevision                              = "os_build_revision"
	AttrOsDistribution                               = "os_distribution"
	AttrOsPlatform                                   = "os_platform"
	AttrOsVersionInfo                                = "os_version_info"
	AttrOverrideReason                               = "override_reason"
	AttrPermissionToAllowSender                      = "permission_to_allow_sender"
	AttrPermissionToBlockSender                      = "permission_to_block_sender"
	AttrPermissionToDelete                           = "permission_to_delete"
	AttrPermissionToDownload                         = "permission_to_download"
	AttrPermissionToPreview                          = "permission_to_preview"
	AttrPermissionToRelease                          = "permission_to_release"
	AttrPermissionToRequestRelease                   = "permission_to_request_release"
	AttrPermissionToViewHeader                       = "permission_to_view_header"
	AttrPreviousFileName                             = "previous_file_name"
	AttrPreviousFolderPath                           = "previous_folder_path"
	AttrPreviousRegistryKey                          = "previous_registry_key"
	AttrPreviousRegistryValueData                    = "previous_registry_value_data"
	AttrPreviousRegistryValueName                    = "previous_registry_value_name"
	AttrProcessCommandLine                           = "process_command_line"
	AttrProcessCreationTime                          = "process_creation_time"
	AttrProcessId                                    = "process_id"
	AttrProcessIntegrityLevel                        = "process_integrity_level"
	AttrProcessRemoteSessionDeviceName               = "process_remote_session_device_name"
	AttrProcessRemoteSessionIp                       = "process_remote_session_ip"
	AttrProcessTokenElevation                        = "process_token_elevation"
	AttrProcessUniqueId                              = "process_unique_id"
	AttrProcessVersionInfoCompanyName                = "process_version_info_company_name"
	AttrProcessVersionInfoFileDescription            = "process_version_info_file_description"
	AttrProcessVersionInfoInternalFileName           = "process_version_info_internal_file_name"
	AttrProcessVersionInfoOriginalFileName           = "process_version_info_original_file_name"
	AttrProcessVersionInfoProductName                = "process_version_info_product_name"
	AttrProcessVersionInfoProductVersion             = "process_version_info_product_version"
	AttrProtocol                                     = "protocol"
	AttrPublicIp                                     = "public_ip"
	AttrQuarantineType                               = "quarantine_type"
	AttrReceivedTime                                 = "received_time"
	AttrRecipientAddress                             = "recipient_address"
	AttrRecipientCount                               = "recipient_count"
	AttrRecipientDomain                              = "recipient_domain"
	AttrRecipientEmailAddress                        = "recipient_email_address"
	AttrRecipientObjectId                            = "recipient_object_id"
	AttrRecipientTag                                 = "recipient_tag"
	AttrRegistryDeviceTag                            = "registry_device_tag"
	AttrRegistryKey                                  = "registry_key"
	AttrRegistryValueData                            = "registry_value_data"
	AttrRegistryValueName                            = "registry_value_name"
	AttrRegistryValueType                            = "registry_value_type"
	AttrReleaseStatus                                = "release_status"
	AttrReleased                                     = "released"
	AttrReleasedBy                                   = "released_by"
	AttrReleasedCount                                = "released_count"
	AttrRemoteDeviceName                             = "remote_device_name"
	AttrRemoteIp                                     = "remote_ip"
	AttrRemoteIpType                                 = "remote_ip_type"
	AttrRemotePort                                   = "remote_port"
	AttrRemoteUrl                                    = "remote_url"
	AttrReportId                                     = "report_id"
	AttrReported                                     = "reported"
	AttrRequestAccountDomain                         = "request_account_domain"
	AttrRequestAccountName                           = "request_account_name"
	AttrRequestAccountSid                            = "request_account_sid"
	AttrRequestProtocol                              = "request_protocol"
	AttrRequestSourceIp                              = "request_source_ip"
	AttrRequestSourcePort                            = "request_source_port"
	AttrSenderAddress                                = "sender_address"
	AttrSenderDisplayName                            = "sender_display_name"
	AttrSenderFromAddress                            = "sender_from_address"
	AttrSenderFromDomain                             = "sender_from_domain"
	AttrSenderIpv4                                   = "sender_ipv4"
	AttrSenderIpv6                                   = "sender_ipv6"
	AttrSenderMailFromAddress                        = "sender_mail_from_address"
	AttrSenderMailFromDomain                         = "sender_mail_from_domain"
	AttrSenderObjectId                               = "sender_object_id"
	AttrSensitivityLabel                             = "sensitivity_label"
	AttrSensitivitySubLabel                          = "sensitivity_sub_label"
	AttrSensorHealthState                            = "sensor_health_state"
	AttrSha1                                         = "sha1"
	AttrSha256                                       = "sha256"
	AttrShareName                                    = "share_name"
	AttrSize                                         = "size"
	AttrSubject                                      = "subject"
	AttrSubscriptionId                               = "subscription_id"
	AttrSystemReleased                               = "system_released"
	AttrTagName                                      = "tag_name"
	AttrThreatClassification                         = "threat_classification"
	AttrThreatFamily                                 = "threat_family"
	AttrThreatNames                                  = "threat_names"
	AttrThreatTypes                                  = "threat_types"
	AttrTo                                           = "to"
	AttrUrlCount                                     = "url_count"
	AttrUserLevelAction                              = "user_level_action"
	AttrUserLevelPolicy                              = "user_level_policy"
	AttrVendor                                       = "vendor"

	// Deferred-companion tables (#106 tail: devicenetworkinfo, devicefilecertificateinfo,
	// emailurlinfo, emailattachmentinfo, identitylogonevents, deviceimageloadevents,
	// identityinfo, cloudappevents).
	AttrAccountDisplayName              = "account_display_name"
	AttrAccountId                       = "account_id"
	AttrAccountType                     = "account_type"
	AttrActivityObjects                 = "activity_objects"
	AttrAddress                         = "address"
	AttrAppInstanceId                   = "app_instance_id"
	AttrAuditSource                     = "audit_source"
	AttrBlastRadius                     = "blast_radius"
	AttrCertificateCountersignatureTime = "certificate_countersignature_time"
	AttrCertificateCreationTime         = "certificate_creation_time"
	AttrCertificateExpirationTime       = "certificate_expiration_time"
	AttrCertificateSerialNumber         = "certificate_serial_number"
	AttrChangeSource                    = "change_source"
	AttrCity                            = "city"
	AttrCloudSid                        = "cloud_sid"
	AttrCompanyName                     = "company_name"
	AttrConnectedNetworks               = "connected_networks"
	AttrCountry                         = "country"
	AttrCountryCode                     = "country_code"
	AttrCriticalityLevel                = "criticality_level"
	AttrCrlDistributionPointUrls        = "crl_distribution_point_urls"
	AttrDefaultGateways                 = "default_gateways"
	AttrDeletedDateTime                 = "deleted_date_time"
	AttrDepartment                      = "department"
	AttrDestinationDeviceName           = "destination_device_name"
	AttrDestinationIpAddress            = "destination_ip_address"
	AttrDestinationPort                 = "destination_port"
	AttrDistinguishedName               = "distinguished_name"
	AttrDnsAddresses                    = "dns_addresses"
	AttrEmailAddress                    = "email_address"
	AttrEmployeeId                      = "employee_id"
	AttrFileExtension                   = "file_extension"
	AttrFileType                        = "file_type"
	AttrGivenName                       = "given_name"
	AttrIdentityEnvironment             = "identity_environment"
	AttrIdentityId                      = "identity_id"
	AttrIpAddresses                     = "ip_addresses"
	AttrIpCategory                      = "ip_category"
	AttrIpTags                          = "ip_tags"
	AttrIpv4Dhcp                        = "ipv4_dhcp"
	AttrIpv6Dhcp                        = "ipv6_dhcp"
	AttrIsAccountEnabled                = "is_account_enabled"
	AttrIsAdminOperation                = "is_admin_operation"
	AttrIsAnonymousProxy                = "is_anonymous_proxy"
	AttrIsClickedThrough                = "is_clicked_through"
	AttrIsExternalUser                  = "is_external_user"
	AttrIsImpersonated                  = "is_impersonated"
	AttrIsRootSignerMicrosoft           = "is_root_signer_microsoft"
	AttrIsSigned                        = "is_signed"
	AttrIsp                             = "isp"
	AttrIssuerHash                      = "issuer_hash"
	AttrJobTitle                        = "job_title"
	AttrLastSeenForUser                 = "last_seen_for_user"
	AttrMacAddress                      = "mac_address"
	AttrManager                         = "manager"
	AttrNetworkAdapterName              = "network_adapter_name"
	AttrNetworkAdapterStatus            = "network_adapter_status"
	AttrNetworkAdapterType              = "network_adapter_type"
	AttrNetworkAdapterVendor            = "network_adapter_vendor"
	AttrOauthAppId                      = "oauth_app_id"
	AttrObjectName                      = "object_name"
	AttrOnPremObjectId                  = "on_prem_object_id"
	AttrOnPremSid                       = "on_prem_sid"
	AttrOtherMailAddresses              = "other_mail_addresses"
	AttrPhone                           = "phone"
	AttrPort                            = "port"
	AttrPrivilegedEntraPimRoles         = "privileged_entra_pim_roles"
	AttrRawEventData                    = "raw_event_data"
	AttrRiskLevelDetails                = "risk_level_details"
	AttrSessionData                     = "session_data"
	AttrSignatureType                   = "signature_type"
	AttrSigner                          = "signer"
	AttrSignerHash                      = "signer_hash"
	AttrSipProxyAddress                 = "sip_proxy_address"
	AttrSourceId                        = "source_id"
	AttrSourceProvider                  = "source_provider"
	AttrSourceProviders                 = "source_providers"
	AttrSurname                         = "surname"
	AttrTags                            = "tags"
	AttrTargetAccountDisplayName        = "target_account_display_name"
	AttrTargetDeviceName                = "target_device_name"
	AttrTunnelType                      = "tunnel_type"
	AttrUncommonForUser                 = "uncommon_for_user"
	AttrUrl                             = "url"
	AttrUrlChain                        = "url_chain"
	AttrUrlChainId                      = "url_chain_id"
	AttrUrlChainPosition                = "url_chain_position"
	AttrUrlDomain                       = "url_domain"
	AttrUrlLocation                     = "url_location"
	AttrUserAccountControl              = "user_account_control"
	AttrUserAgentTags                   = "user_agent_tags"

	// #241 tables: behaviorinfo/behaviorentities (Defender behavior analytics,
	// the alert-info+evidence shape joined by BehaviorId) and
	// messageevents/messageurlinfo (Teams message hygiene, the email+emailurl
	// shape joined by TeamsMessageId).
	AttrBehaviorId         = "behavior_id"
	AttrDataSources        = "data_sources"
	AttrDetailedEntityRole = "detailed_entity_role"
	AttrEndTime            = "end_time"
	AttrEntityRole         = "entity_role"
	AttrGroupId            = "group_id"
	AttrGroupName          = "group_name"
	AttrIsExternalThread   = "is_external_thread"
	AttrIsOwnedThread      = "is_owned_thread"
	AttrLastEditedTime     = "last_edited_time"
	AttrMessageId          = "message_id"
	AttrMessageSubtype     = "message_subtype"
	AttrMessageType        = "message_type"
	AttrMessageVersion     = "message_version"
	AttrParentMessageId    = "parent_message_id"
	AttrRecipientDetails   = "recipient_details"
	AttrSafetyTip          = "safety_tip"
	AttrSenderEmailAddress = "sender_email_address"
	AttrSenderType         = "sender_type"
	AttrStartTime          = "start_time"
	AttrTeamsMessageId     = "teams_message_id"
	AttrThreadId           = "thread_id"
	AttrThreadName         = "thread_name"
	AttrThreadSubType      = "thread_sub_type"
	AttrThreadType         = "thread_type"
)

// MDO policy-posture keys (#250) — defender.mdo_policies, the Microsoft Defender
// for Office 365 policy collector reached over the Exchange Online admin API
// (EXO registration path). policy_type/policy_name are reused from
// attrs_intune.go, name from attrs_purview.go, is_default from attrs_entra.go and
// enabled/action from the other domain files; only the keys below are new. Every
// key is a semconv.Attr* constant (Gate B) with a value that duplicates no other
// constant (Gate A).
const (
	// AttrProtection is the bounded protection-name label on
	// defender.mdo.protection_enabled (zap, spam_zap, safe_links_email, ...): a
	// small closed set, so it is a legal metric label.
	AttrProtection = "protection"

	// String action/threshold-name fields carried on the defender.mdo_policy twin.
	AttrRecommendedPolicyType               = "recommended_policy_type"
	AttrSpamAction                          = "spam_action"
	AttrHighConfidenceSpamAction            = "high_confidence_spam_action"
	AttrPhishSpamAction                     = "phish_spam_action"
	AttrHighConfidencePhishAction           = "high_confidence_phish_action"
	AttrBulkSpamAction                      = "bulk_spam_action"
	AttrFileTypeAction                      = "file_type_action"
	AttrAuthenticationFailAction            = "authentication_fail_action"
	AttrDmarcRejectAction                   = "dmarc_reject_action"
	AttrDmarcQuarantineAction               = "dmarc_quarantine_action"
	AttrMailboxIntelligenceProtectionAction = "mailbox_intelligence_protection_action"
	AttrTargetedUserProtectionAction        = "targeted_user_protection_action"
	AttrTargetedDomainProtectionAction      = "targeted_domain_protection_action"
	AttrSafeAttachmentAction                = "safe_attachment_action"

	// Numeric threshold/retention fields on the defender.mdo_policy twin.
	AttrBulkThreshold             = "bulk_threshold"
	AttrPhishThresholdLevel       = "phish_threshold_level"
	AttrQuarantineRetentionPeriod = "quarantine_retention_period"

	// Boolean posture toggles on the defender.mdo_policy twin. Emitted even when
	// false (#114): false is the answer an operator filters for (a protection
	// switched off on a policy that supports it).
	AttrZapEnabled                   = "zap_enabled"
	AttrSpamZapEnabled               = "spam_zap_enabled"
	AttrPhishZapEnabled              = "phish_zap_enabled"
	AttrFileFilterEnabled            = "file_filter_enabled"
	AttrSpoofIntelligenceEnabled     = "spoof_intelligence_enabled"
	AttrMailboxIntelligenceEnabled   = "mailbox_intelligence_enabled"
	AttrSafeDocsEnabled              = "safe_docs_enabled"
	AttrSafeLinksEmailEnabled        = "safe_links_email_enabled"
	AttrSafeLinksTeamsEnabled        = "safe_links_teams_enabled"
	AttrSafeLinksOfficeEnabled       = "safe_links_office_enabled"
	AttrSafeAttachmentsEnabled       = "safe_attachments_enabled"
	AttrScanUrlsEnabled              = "scan_urls_enabled"
	AttrAllowClickThrough            = "allow_click_through"
	AttrDeliverMessageAfterScan      = "deliver_message_after_scan"
	AttrEnableForInternalSenders     = "enable_for_internal_senders"
	AttrEnableTargetedUserProtection = "enable_targeted_user_protection"
	AttrEnableTargetedDomainsProt    = "enable_targeted_domains_protection"
	AttrAllowSafeDocsOpen            = "allow_safe_docs_open"
	AttrEnableAtpForSpoTeamsOdb      = "enable_atp_for_spo_teams_odb"
	AttrHonorDmarcPolicy             = "honor_dmarc_policy"
)

// Advanced-hunting DeviceTvm* attributes (#249) — the threat-and-vulnerability-
// management posture reached over the Graph runHuntingQuery API. Reused from
// other domains where a key already exists: AttrOsPlatform (above), AttrOsVersion
// and AttrDeviceId/AttrDeviceName (intune), AttrIsCompliant (entra), AttrSeverity
// (shared). Every value below is the snake_case of a column read verbatim off a
// live query result, never a docs field.
const (
	// defender.vulnerabilities — per-device software-vulnerability rows, joined
	// server-side to the KB table for CVSS/EPSS/exploit availability.
	AttrSoftwareVendor            = "software_vendor"
	AttrSoftwareName              = "software_name"
	AttrSoftwareVersion           = "software_version"
	AttrCveId                     = "cve_id"
	AttrExploitAvailable          = "exploit_available"
	AttrRecommendedSecurityUpdate = "recommended_security_update"
	AttrCveMitigationStatus       = "cve_mitigation_status"
	AttrCvssScore                 = "cvss_score"
	AttrEpssScore                 = "epss_score"
	AttrCvssVector                = "cvss_vector"
	AttrPublishedDate             = "published_date"

	// defender.secure_config — per-device secure-configuration assessment rows.
	AttrConfigurationCategory    = "configuration_category"
	AttrConfigurationSubcategory = "configuration_subcategory"
	AttrConfigurationId          = "configuration_id"
	AttrConfigurationImpact      = "configuration_impact"

	// defender.software_inventory — per-device installed-software rows.
	AttrEndOfSupportStatus = "end_of_support_status"
	AttrEndOfSupportDate   = "end_of_support_date"
	AttrProductCodeCpe     = "product_code_cpe"
)

// OAuthAppInfo attributes (#252) — the Defender for Cloud Apps OAuth-app
// inventory, reached over the advanced-hunting query API. Reused where a key
// exists: AttrOauthAppId (above), AttrAppName (intune), AttrServicePrincipalId
// (entra). Every value is the snake_case of a column read verbatim off a live
// query result.
const (
	AttrPrivilegeLevel        = "privilege_level"
	AttrAppStatus             = "app_status"
	AttrAppOrigin             = "app_origin"
	AttrAdminConsented        = "admin_consented"
	AttrRiskScore             = "risk_score"
	AttrConsentedUsersCount   = "consented_users_count"
	AttrAppOwnerTenantId      = "app_owner_tenant_id"
	AttrLastUsedTime          = "last_used_time"
	AttrAddedOnTime           = "added_on_time"
	AttrVerifiedPublisherName = "verified_publisher_name"
	AttrVerifiedPublisherId   = "verified_publisher_id"
	AttrIsVerifiedPublisher   = "is_verified_publisher"
	AttrPermissionValues      = "permission_values"
	AttrPermissionsCount      = "permissions_count"
)
