package semconv

// Attribute keys used only by m365.* collectors.
const (
	AttrActionRequiredByDateTime     = "action_required_by_date_time"
	AttrActorIds                     = "actor_ids"
	AttrAzureAdEventType             = "azure_ad_event_type"
	AttrClientIp                     = "client_ip"
	AttrExtendedPropertyNames        = "extended_property_names"
	AttrExtendedPropertyValues       = "extended_property_values"
	AttrExternalResharingEnabled     = "external_resharing_enabled"
	AttrFeature                      = "feature"
	AttrFeatureGroup                 = "feature_group"
	AttrHasAttachments               = "has_attachments"
	AttrIdleSessionSignoutEnabled    = "idle_session_signout_enabled"
	AttrImpactDescription            = "impact_description"
	AttrIsMajorChange                = "is_major_change"
	AttrIsResolved                   = "is_resolved"
	AttrLastModifiedDateTime         = "last_modified_date_time"
	AttrLegacyAuthEnabled            = "legacy_auth_enabled"
	AttrMessageBody                  = "message_body"
	AttrObjectId                     = "object_id"
	AttrOperation                    = "operation"
	AttrOrganizationId               = "organization_id"
	AttrOrigin                       = "origin"
	AttrRecordType                   = "record_type"
	AttrRecordTypeId                 = "record_type_id"
	AttrResultStatus                 = "result_status"
	AttrService                      = "service"
	AttrServices                     = "services"
	AttrSharingAllowedDomains        = "sharing_allowed_domains"
	AttrSharingBlockedDomains        = "sharing_blocked_domains"
	AttrSharingCapability            = "sharing_capability"
	AttrSharingDomainRestrictionMode = "sharing_domain_restriction_mode"
	AttrUnmanagedSyncRestricted      = "unmanaged_sync_restricted"
	AttrUserKey                      = "user_key"
	AttrUserType                     = "user_type"
	AttrUserTypeId                   = "user_type_id"
	AttrVersion                      = "version"
	AttrWorkload                     = "workload"
)
