package semconv

// Attribute keys used only by m365.* collectors.
const (
	AttrActionRequiredByDateTime     = "action_required_by_date_time"
	AttrActiveFileCount              = "active_file_count"
	AttrActorIds                     = "actor_ids"
	AttrAzureAdEventType             = "azure_ad_event_type"
	AttrClientIp                     = "client_ip"
	AttrDriveType                    = "drive_type"
	AttrExtendedPropertyNames        = "extended_property_names"
	AttrExtendedPropertyValues       = "extended_property_values"
	AttrExternalResharingEnabled     = "external_resharing_enabled"
	AttrFeature                      = "feature"
	AttrFeatureGroup                 = "feature_group"
	AttrFileCount                    = "file_count"
	AttrHasAttachments               = "has_attachments"
	AttrIdleSessionSignoutEnabled    = "idle_session_signout_enabled"
	AttrImpactDescription            = "impact_description"
	AttrIsDeleted                    = "is_deleted"
	AttrIsMajorChange                = "is_major_change"
	AttrIsResolved                   = "is_resolved"
	AttrLastActivityDate             = "last_activity_date"
	AttrLastModifiedDateTime         = "last_modified_date_time"
	AttrLegacyAuthEnabled            = "legacy_auth_enabled"
	AttrMessageBody                  = "message_body"
	AttrNamesConcealed               = "names_concealed"
	AttrObjectId                     = "object_id"
	AttrOperation                    = "operation"
	AttrOrganizationId               = "organization_id"
	AttrOrigin                       = "origin"
	AttrOwnerDisplayName             = "owner_display_name"
	AttrOwnerPrincipalName           = "owner_principal_name"
	AttrQuotaState                   = "quota_state"
	AttrRecordType                   = "record_type"
	AttrRecordTypeId                 = "record_type_id"
	AttrReleaseTo                    = "release_to"
	AttrRequestType                  = "request_type"
	AttrResultStatus                 = "result_status"
	AttrRootWebTemplate              = "root_web_template"
	AttrService                      = "service"
	AttrServices                     = "services"
	AttrSharingAllowedDomains        = "sharing_allowed_domains"
	AttrSharingBlockedDomains        = "sharing_blocked_domains"
	AttrSharingCapability            = "sharing_capability"
	AttrSharingDomainRestrictionMode = "sharing_domain_restriction_mode"
	AttrSiteId                       = "site_id"
	AttrSiteUrl                      = "site_url"
	AttrStorageAllocatedBytes        = "storage_allocated_bytes"
	AttrStorageRemainingBytes        = "storage_remaining_bytes"
	AttrStorageUsedBytes             = "storage_used_bytes"
	AttrUnmanagedSyncRestricted      = "unmanaged_sync_restricted"
	AttrUserKey                      = "user_key"
	AttrUserType                     = "user_type"
	AttrUserTypeId                   = "user_type_id"
	AttrVersion                      = "version"
	AttrWorkload                     = "workload"
)
