// Package signalcatalog aggregates every collector package's committed
// testdata/signals.json golden into ONE machine-readable catalog of what
// graph2otel actually emits — spec/signal-catalog.json — and derives the
// Prometheus name each metric lands under after OTLP ingest.
//
// # Why this is an aggregation and not an extraction (#218)
//
// #218 was filed asking for "a machine-readable list of every metric
// graph2otel emits, analogous to tailscale2otel's tools/metricscatalog", on the
// stated premise that graph2otel has no catalog today. That premise was
// wrong. The catalog already exists in distributed form: 139 per-package
// goldens carrying name, unit, aggregation kind and attribute keys for every
// metric, and the event name and attribute keys for every log — and it is
// already better than the tool it proposed copying, because it is captured from
// what the tests EMIT (internal/signalcapture) rather than parsed out of
// source. A metric that exists in code but never reaches the wire does not
// appear in it.
//
// So this package writes no new truth. It merges files that already exist, are
// already regenerated by scripts/regen-generated.sh, and are already drift-gated
// (#140). The self-updating property #218 actually wanted comes free: a new
// collector's golden is written by the existing regen step, and the aggregate
// picks it up with no human step and no second list to maintain.
//
// # What it adds on top of the goldens
//
// Three derived fields the goldens deliberately do not carry, because each is a
// property of the CONSUMER rather than of the emission:
//
//   - PrometheusName — the name a dashboard or alert must actually query, after
//     the OTLP→Prometheus normalization described below. A dashboard built on
//     the OTEL name matches nothing.
//   - Additive — semconv.MetricAdditive, so a panel builder can pick sum() over
//     avg() from the catalog instead of guessing. Summing four thousand health
//     scores emits a number that was never measured (#235).
//   - Domain — the leading namespace segment, which is the unit #162's log-panel
//     coverage is gated on.
package signalcatalog

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"github.com/rknightion/graph2otel/internal/semconv"
	"github.com/rknightion/graph2otel/internal/signalcapture"
)

// CatalogPath is the committed aggregate, relative to the repo root.
const CatalogPath = "spec/signal-catalog.json"

// goldenGlob matches every collector package's committed capture, relative to
// the repo root. It is the same glob scripts/regen-generated.sh drives its
// -update run from, so the two cannot see different sets of packages.
const goldenGlob = "internal/collectors/*/*/testdata/signals.json"

// Metric is one emitted metric, merged across every package that emits it.
type Metric struct {
	Name string `json:"name"`
	// PrometheusName is what to put in a PromQL query. See PrometheusName.
	PrometheusName string `json:"prometheus_name"`
	Unit           string `json:"unit"`
	// Kind is the SDK aggregation kind: "gauge", "sum" or "histogram".
	Kind string `json:"kind"`
	// Additive reports whether these series may legally be summed together
	// (semconv.MetricAdditive). A non-additive metric wants avg()/max(), never
	// sum(): the sum of a set of scores is a number nobody measured.
	Additive bool `json:"additive"`
	// Domain is the leading namespace segment: entra, intune, m365, purview,
	// defender, mdca or graph2otel.
	Domain   string   `json:"domain"`
	AttrKeys []string `json:"attr_keys"`
	// Packages are the collector packages observed emitting this metric,
	// relative to the repo root.
	Packages []string `json:"packages"`
}

// LogEvent is one emitted log event name, merged across every package that
// emits it. Attribute keys are the UNION over those packages — two transports
// of one signal (entra.signin over graph and over blob) legitimately differ.
type LogEvent struct {
	EventName string   `json:"event_name"`
	Domain    string   `json:"domain"`
	AttrKeys  []string `json:"attr_keys"`
	Packages  []string `json:"packages"`
}

// Catalog is the whole emitted surface.
type Catalog struct {
	// PackageCount is how many goldens were merged. It exists so a consumer
	// (and TestLoadAggregatesEveryGolden) can tell "the tree shrank" from "the
	// glob stopped matching".
	PackageCount int        `json:"package_count"`
	Domains      []string   `json:"domains"`
	Metrics      []Metric   `json:"metrics"`
	Logs         []LogEvent `json:"logs"`
}

// MetricNames returns every cataloged metric name, sorted.
func (c Catalog) MetricNames() []string {
	out := make([]string, 0, len(c.Metrics))
	for _, m := range c.Metrics {
		out = append(out, m.Name)
	}
	return out
}

// Load merges every committed golden under root into one Catalog.
//
// A metric emitted by several packages is merged, not duplicated: the attribute
// keys are unioned (a shared mapper reached over two transports sets different
// keys — entra.signin is the live case) and every emitting package is recorded.
// Unit and kind are taken from the FIRST package in sorted order; they cannot
// legally disagree, and cmd/graph2otel's tree walk is what proves it.
func Load(root string) (Catalog, error) {
	paths, err := filepath.Glob(filepath.Join(root, filepath.FromSlash(goldenGlob)))
	if err != nil {
		return Catalog{}, fmt.Errorf("signalcatalog: globbing %s: %w", goldenGlob, err)
	}
	if len(paths) == 0 {
		return Catalog{}, fmt.Errorf("signalcatalog: no goldens matched %s under %s — "+
			"regenerate with `scripts/regen-generated.sh signals`", goldenGlob, root)
	}
	sort.Strings(paths)

	metrics := map[string]*Metric{}
	logs := map[string]*LogEvent{}
	metricKeys := map[string]map[string]struct{}{}
	logKeys := map[string]map[string]struct{}{}

	for _, p := range paths {
		body, err := os.ReadFile(p) //nolint:gosec // G304: path comes from a fixed in-repo glob
		if err != nil {
			return Catalog{}, fmt.Errorf("signalcatalog: reading %s: %w", p, err)
		}
		var sig signalcapture.Signals
		if err := json.Unmarshal(body, &sig); err != nil {
			return Catalog{}, fmt.Errorf("signalcatalog: parsing %s: %w", p, err)
		}
		pkg := packageOf(root, p)

		for _, m := range sig.Metrics {
			cur, ok := metrics[m.Name]
			if !ok {
				cur = &Metric{
					Name:           m.Name,
					PrometheusName: PrometheusName(m.Name, m.Unit, m.Kind),
					Unit:           m.Unit,
					Kind:           m.Kind,
					Additive:       semconv.MetricAdditive(m.Unit, m.Kind),
					Domain:         domainOf(m.Name),
				}
				metrics[m.Name] = cur
				metricKeys[m.Name] = map[string]struct{}{}
			}
			for _, k := range m.AttrKeys {
				metricKeys[m.Name][k] = struct{}{}
			}
			cur.Packages = appendUnique(cur.Packages, pkg)
		}
		for _, l := range sig.Logs {
			cur, ok := logs[l.EventName]
			if !ok {
				cur = &LogEvent{EventName: l.EventName, Domain: domainOf(l.EventName)}
				logs[l.EventName] = cur
				logKeys[l.EventName] = map[string]struct{}{}
			}
			for _, k := range l.AttrKeys {
				logKeys[l.EventName][k] = struct{}{}
			}
			cur.Packages = appendUnique(cur.Packages, pkg)
		}
	}

	cat := Catalog{PackageCount: len(paths)}
	domains := map[string]struct{}{}
	for name, m := range metrics {
		m.AttrKeys = sortedSet(metricKeys[name])
		sort.Strings(m.Packages)
		domains[m.Domain] = struct{}{}
		cat.Metrics = append(cat.Metrics, *m)
	}
	for name, l := range logs {
		l.AttrKeys = sortedSet(logKeys[name])
		sort.Strings(l.Packages)
		domains[l.Domain] = struct{}{}
		cat.Logs = append(cat.Logs, *l)
	}
	sort.Slice(cat.Metrics, func(i, j int) bool { return cat.Metrics[i].Name < cat.Metrics[j].Name })
	sort.Slice(cat.Logs, func(i, j int) bool { return cat.Logs[i].EventName < cat.Logs[j].EventName })
	cat.Domains = sortedSet(domains)
	return cat, nil
}

// Render marshals a Catalog to the exact bytes the committed file must hold.
func Render(c Catalog) ([]byte, error) {
	body, err := json.MarshalIndent(c, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(body, '\n'), nil
}

// ReadFile loads the committed catalog from root.
func ReadFile(root string) (Catalog, error) {
	path := filepath.Join(root, filepath.FromSlash(CatalogPath))
	body, err := os.ReadFile(path) //nolint:gosec // G304: fixed in-repo path
	if err != nil {
		return Catalog{}, fmt.Errorf("signalcatalog: reading %s: %w", path, err)
	}
	var c Catalog
	if err := json.Unmarshal(body, &c); err != nil {
		return Catalog{}, fmt.Errorf("signalcatalog: parsing %s: %w", path, err)
	}
	return c, nil
}

// packageOf turns an absolute golden path back into the repo-relative package
// directory that owns it.
func packageOf(root, goldenPath string) string {
	dir := filepath.Dir(filepath.Dir(goldenPath)) // strip /testdata/signals.json
	rel, err := filepath.Rel(root, dir)
	if err != nil {
		return filepath.ToSlash(dir)
	}
	return filepath.ToSlash(rel)
}

func domainOf(name string) string {
	if i := strings.IndexByte(name, '.'); i > 0 {
		return name[:i]
	}
	return name
}

func appendUnique(s []string, v string) []string {
	if slices.Contains(s, v) {
		return s
	}
	return append(s, v)
}

func sortedSet(m map[string]struct{}) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// unitSuffixes is the OTLP→Prometheus unit suffix table, as implemented by the
// OpenTelemetry Prometheus translator that Grafana Cloud (Mimir) runs on
// ingest. A unit absent from this table contributes NO suffix — which is why
// "MB" (not a UCUM name; the translator knows "MBy") is silently suffix-less.
var unitSuffixes = map[string]string{
	"d": "days", "h": "hours", "min": "minutes", "s": "seconds",
	"ms": "milliseconds", "us": "microseconds", "ns": "nanoseconds",
	"By": "bytes", "KiBy": "kibibytes", "MiBy": "mebibytes", "GiBy": "gibibytes", "TiBy": "tebibytes",
	"KBy": "kilobytes", "MBy": "megabytes", "GBy": "gigabytes", "TBy": "terabytes",
	"m": "meters", "V": "volts", "A": "amperes", "J": "joules", "W": "watts", "g": "grams",
	"Cel": "celsius", "Hz": "hertz", "%": "percent",
}

// PrometheusName derives the metric name a PromQL query must use, from the OTEL
// name, UCUM unit and SDK aggregation kind.
//
// # Why this is derived rather than written down
//
// graph2otel is OTLP-only — there is no Prometheus endpoint to read the real
// names off. The names only exist after a backend normalizes them, so any
// hand-written list of them is a second source of truth that drifts the moment
// a unit changes. Deriving means a unit edit moves the query with it.
//
// # The algorithm
//
// It reproduces the OpenTelemetry Prometheus translator with metric suffixes
// enabled, which is what Grafana Cloud runs:
//
//  1. Split the name on every character that is not [A-Za-z0-9:]; the tokens
//     rejoin with "_", so dots become underscores.
//  2. Strip UCUM annotations ("{device}") from the unit. An annotation-only unit
//     contributes no suffix — it names what is counted, not a dimension.
//  3. Append the unit's suffix word UNLESS that word is already one of the name's
//     tokens. This is why intune.connector.heartbeat_age_seconds (unit "s") does
//     not become ..._seconds_seconds, and why intune.apple_token.days_until_expiry
//     (unit "d") gains nothing at all — "days" is already in there.
//  4. A dimensionless ("1") GAUGE gains "ratio". A dimensionless SUM does not:
//     it is a counter, and step 5 gives it "total" instead.
//  5. A sum gains a trailing "total".
//
// Histograms keep their base name here; their _bucket / _sum / _count series
// hang off it at query time.
//
// # Its honest limit
//
// Exact normalization is a property of the reader's OTLP pipeline, not of
// graph2otel — some setups preserve original names or omit suffixes entirely
// (docs/signals.md says so, and alerts/README.md repeats it). This is the
// convention the shipped dashboards and alert rules are built against, and the
// [live] cases in TestPrometheusName were verified against a live Grafana Cloud
// Mimir. Treat it as the convention, not a byte-exact promise.
func PrometheusName(name, unit, kind string) string {
	tokens := strings.FieldsFunc(name, func(r rune) bool {
		return (r < 'a' || r > 'z') && (r < 'A' || r > 'Z') && (r < '0' || r > '9') && r != ':'
	})

	main := stripAnnotations(unit)
	if suffix, ok := unitSuffixes[main]; ok && suffix != "" && !slices.Contains(tokens, suffix) {
		tokens = append(tokens, suffix)
	}
	if main == "1" && kind == "gauge" && !slices.Contains(tokens, "ratio") {
		tokens = append(tokens, "ratio")
	}
	if kind == "sum" {
		for len(tokens) > 0 && tokens[len(tokens)-1] == "total" {
			tokens = tokens[:len(tokens)-1]
		}
		tokens = append(tokens, "total")
	}
	return strings.Join(tokens, "_")
}

// stripAnnotations removes every UCUM annotation ("{device}") from a unit,
// leaving the dimensional part. "{device}" -> "", "s" -> "s".
func stripAnnotations(unit string) string {
	for {
		open := strings.IndexByte(unit, '{')
		if open < 0 {
			return strings.TrimSpace(unit)
		}
		closed := strings.IndexByte(unit[open:], '}')
		if closed < 0 {
			return strings.TrimSpace(unit[:open])
		}
		unit = unit[:open] + unit[open+closed+1:]
	}
}
