#!/usr/bin/env bash
#
# Regenerate the repo's committed *generated* artifacts so they never drift from
# their sources (drift is what fails the `go test` / CI gates). Each artifact is
# a pure function of its inputs:
#
#   docs/env-vars.md    <- config.example.yaml        (TestEnvReferenceDocInSync -update)
#   docs/collectors.md  <- the collector registry     (TestCollectorReferenceDocInSync -update)
#                          + internal/collectordoc/annotations.go
#                          + internal/collectors/*/*/testdata/signals.json (#140)
#   internal/collectors/*/*/testdata/signals.json
#                       <- what each package's tests really emit (signalcapture.Main -update)
#
# Order matters: docs/collectors.md's signal columns are now READ from the
# committed testdata/signals.json goldens (#140), so regen_signals MUST run
# before regen_collectordoc — regenerating collectordoc first would render
# against whatever goldens happened to already be on disk, not the ones this
# run is about to produce. The `all` target below is ordered accordingly.
#
# All three are generated by a golden test's -update mode (root module; no
# separate tool), and all three drift gates are those same tests under a plain
# `go test` run — so `make check` already fails on a stale doc. This wrapper is
# just the "regenerate it for me" convenience.
#
#   envref      The env-var reference table, generated from config.example.yaml.
#
#   collectordoc  The collector reference tables, generated by walking the live
#               registry (collectors.All + WindowAll + BlobAll + O365All) for the facts it
#               knows — interval, lag, license gate, beta flag, declared scopes,
#               blob container and cursor key — merged with the hand-written
#               prose in internal/collectordoc/annotations.go for what a
#               collector is for and its endpoints, and the emitted-signal
#               columns read from each collector package's committed
#               testdata/signals.json golden (#140). Only the block between the
#               generated markers in docs/collectors.md is rewritten; the notes
#               around it are hand-written. A collector with no annotation
#               fails TestCollectorAnnotationsCoverEveryCollector by name, and
#               a collector whose package has no signals.json golden fails
#               Rows directly — both gates are the point, and no regeneration
#               silences either.
#
# Usage:
#   scripts/regen-generated.sh              # regenerate everything
#   scripts/regen-generated.sh envref       # just docs/env-vars.md
#   scripts/regen-generated.sh collectordoc # just docs/collectors.md
#   scripts/regen-generated.sh signals      # just the emitted-signal captures
#
# NOTE — Helm chart docs/schema are NOT yet wired here. The chart's values.yaml
# `config:` block is kept in sync with the config struct by the pure-`go test`
# gate TestHelmValuesConfigCoversEveryKey (no external tooling needed). If/when
# helm-docs + values.schema.json generation lands (see the sibling
# tailscale2otel repo's scripts/regen-generated.sh + .github/workflows/helm.yml),
# add `helm-docs` / `helm-schema` targets here.
#
# A missing tool is a loud SKIP (not a failure) so the hook never blocks a
# commit — CI's `go test` gate remains the hard backstop. A regeneration that
# actually errors (e.g. the code doesn't compile) DOES fail.
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"

note() { printf '  regen: %s\n' "$1"; }
skip() { printf '  regen: SKIP %s\n' "$1" >&2; }

regen_envref() {
  if ! command -v go >/dev/null 2>&1; then
    skip "go not installed -> docs/env-vars.md not regenerated (CI will gate it)"
    return 0
  fi
  note "docs/env-vars.md (config env-var reference)"
  go test -C "$ROOT" ./internal/config -run TestEnvReferenceDocInSync -update -count=1 >/dev/null
}

regen_collectordoc() {
  if ! command -v go >/dev/null 2>&1; then
    skip "go not installed -> docs/collectors.md not regenerated (CI will gate it)"
    return 0
  fi
  note "docs/collectors.md (collector reference)"
  go test -C "$ROOT" ./cmd/graph2otel -run TestCollectorReferenceDocInSync -update -count=1 >/dev/null
}

# regen_signals rewrites every collector package's testdata/signals.json from what
# that package's tests ACTUALLY emit (#140). Unlike the two artifacts above these
# are not a doc — they are the captured truth a doc can later be built from, and
# the drift gate that fails `go test` when a collector's emissions change.
#
# Scoped per package rather than `./internal/collectors/...`: -update is defined
# only by packages that install signalcapture.Main, and Go passes the flag to
# every package in the pattern, so a tree-wide run fails on the ones that do not
# define it. Driving from the signalgate_test.go files keeps this list honest —
# it cannot go stale relative to which packages actually have the gate.
regen_signals() {
  if ! command -v go >/dev/null 2>&1; then
    skip "go not installed -> testdata/signals.json not regenerated (CI will gate it)"
    return 0
  fi
  note "internal/collectors/*/*/testdata/signals.json (emitted-signal captures)"
  local pkgs=()
  while IFS= read -r f; do
    pkgs+=("./$(dirname "$f")")
  done < <(cd "$ROOT" && git ls-files 'internal/collectors/*/*/signalgate_test.go')
  [ ${#pkgs[@]} -eq 0 ] && { skip "no collector package installs signalcapture.Main"; return 0; }
  go test -C "$ROOT" "${pkgs[@]}" -update -count=1 >/dev/null
}

main() {
  local targets=("$@")
  [ ${#targets[@]} -eq 0 ] && targets=(all)

  local do_envref=0
  local do_collectordoc=0
  local do_signals=0
  for t in "${targets[@]}"; do
    case "$t" in
      all)          do_envref=1; do_collectordoc=1; do_signals=1 ;;
      envref)       do_envref=1 ;;
      collectordoc) do_collectordoc=1 ;;
      signals)      do_signals=1 ;;
      *) printf 'regen-generated.sh: unknown target %q\n' "$t" >&2; exit 2 ;;
    esac
  done

  [ "$do_envref" = 1 ] && regen_envref
  [ "$do_signals" = 1 ] && regen_signals
  [ "$do_collectordoc" = 1 ] && regen_collectordoc
  return 0
}

main "$@"
