#!/usr/bin/env bash
#
# Regenerate the repo's committed *generated* artifacts so they never drift from
# their sources (drift is what fails the `go test` / CI gates). Each artifact is
# a pure function of its inputs:
#
#   docs/env-vars.md    <- config.example.yaml        (TestEnvReferenceDocInSync -update)
#   docs/collectors.md  <- the collector registry     (TestCollectorReferenceDocInSync -update)
#                          + internal/collectordoc/annotations.go
#
# Both are generated by a golden test's -update mode (root module; no separate
# tool), and both drift gates are those same tests under a plain `go test` run —
# so `make check` already fails on a stale doc. This wrapper is just the
# "regenerate it for me" convenience.
#
#   envref      The env-var reference table, generated from config.example.yaml.
#
#   collectordoc  The collector reference tables, generated by walking the live
#               registry (collectors.All + WindowAll + BlobAll + O365All) for the facts it
#               knows — interval, lag, license gate, beta flag, declared scopes,
#               blob container and cursor key — merged with the hand-written
#               prose in internal/collectordoc/annotations.go for the facts it
#               does not (what a collector is for, its endpoints, what it emits).
#               Only the block between the generated markers in
#               docs/collectors.md is rewritten; the notes around it are
#               hand-written. A collector with no annotation fails
#               TestCollectorAnnotationsCoverEveryCollector by name — that gate
#               is the point, and no regeneration silences it.
#
# Usage:
#   scripts/regen-generated.sh              # regenerate everything
#   scripts/regen-generated.sh envref       # just docs/env-vars.md
#   scripts/regen-generated.sh collectordoc # just docs/collectors.md
#
# NOTE — Helm chart docs/schema are NOT yet wired here. The chart's values.yaml
# `config:` block is kept in sync with the config struct by the pure-`go test`
# gate TestHelmValuesConfigCoversEveryKey (no external tooling needed). If/when
# helm-docs + values.schema.json generation lands (see the sibling
# tailscale2otel repo's scripts/regen-generated.sh + .github/workflows/helm.yml),
# add `helm-docs` / `helm-schema` targets here.
#
# A missing tool is a loud SKIP (not a failure) so the hook never blocks a
# commit — CI's `go test` gate remains the hard backstop. A regeneration that
# actually errors (e.g. the code doesn't compile) DOES fail.
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"

note() { printf '  regen: %s\n' "$1"; }
skip() { printf '  regen: SKIP %s\n' "$1" >&2; }

regen_envref() {
  if ! command -v go >/dev/null 2>&1; then
    skip "go not installed -> docs/env-vars.md not regenerated (CI will gate it)"
    return 0
  fi
  note "docs/env-vars.md (config env-var reference)"
  go test -C "$ROOT" ./internal/config -run TestEnvReferenceDocInSync -update -count=1 >/dev/null
}

regen_collectordoc() {
  if ! command -v go >/dev/null 2>&1; then
    skip "go not installed -> docs/collectors.md not regenerated (CI will gate it)"
    return 0
  fi
  note "docs/collectors.md (collector reference)"
  go test -C "$ROOT" ./cmd/graph2otel -run TestCollectorReferenceDocInSync -update -count=1 >/dev/null
}

main() {
  local targets=("$@")
  [ ${#targets[@]} -eq 0 ] && targets=(all)

  local do_envref=0
  local do_collectordoc=0
  for t in "${targets[@]}"; do
    case "$t" in
      all)          do_envref=1; do_collectordoc=1 ;;
      envref)       do_envref=1 ;;
      collectordoc) do_collectordoc=1 ;;
      *) printf 'regen-generated.sh: unknown target %q\n' "$t" >&2; exit 2 ;;
    esac
  done

  [ "$do_envref" = 1 ] && regen_envref
  [ "$do_collectordoc" = 1 ] && regen_collectordoc
  return 0
}

main "$@"
